#!/bin/sh /etc/rc.common

START=74

USE_PROCD=1
PROG=/usr/sbin/glite_oam

IFNAME=br-wan

start_service() {
	[ "$(uci -q get dvui.network.opmode)" = "bridge" ] && return

	procd_open_instance
	procd_set_param command ${PROG} ${IFNAME} ${IFNAME} f
	procd_set_param respawn
	procd_close_instance
}

reload_service()
{
	rc_procd stop_service "$@"
	rc_procd start_service "$@"
	return 0
}


stop_service() {
	service_stop ${PROG}
	rm -f /var/run/glite_oam.pid
}

