#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

static char *outname;
static char fn_init_name[80];

#define WARNING_MSG \
	"/******************************************************************\n"\
	" * Please DO NOT EDIT THIS FILE !!!\n"\
	" * This file is automatically generated by hide_str_gen2.\n"\
	" * If you modify this file, your changes can be removed at next build.\n"\
	" ******************************************************************/\n\n"

char *init_def[] = {
	"#ifdef __KERNEL__",
	"#include <linux/version.h>",
	"#include <linux/kernel.h>",
	"#include <linux/module.h>",
	"#include <linux/ctype.h>",
	"#else",
	"#include <stdio.h>",
	"#include <string.h>",
	"#include <ctype.h>",
	"#endif",
	"",
	"#define CB64 \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\"",
	"#define HEXA \"0123456789abcdef\"",
	"#define CPTA \"abcdefghijklmnopqrstuvwxyz\"",
	"#define SYMB \"~`!@#$%^&*()_-+={[}]|\\\\:;\\\"'<,>.?/\"",
	"",
	"#define AL0(x) CB64[26 + ((x)-'a')]",
	"#define AL1(x) tolower(CB64[0 + ((x)-'a')])",
	"#define AL2(x) CPTA[0 + ((x)-'a')]",
	"#define AL3(x) ((((x)>='a')&&((x)<='f')) ? HEXA[10 + ((x)-'a')]:AL1(x))",
	"#define NB0(x) CB64[52+((x)-'0')]",
	"#define NB1(x) HEXA[0+((x)-'0')]",
	"#define NL0 CB64[64]",
	"#define NL1 CPTA[26]",
	"#define NL2 HEXA[16]",
	"#define NL3 SYMB[32]",
	"#define SL0 CB64[63]",
	"#define SL1 SYMB[31]",
	"#define DOT SYMB[29]",
	"#define AST SYMB[9]",
	"#define QST SYMB[30]",
	"",
	NULL
};


void emit_char(FILE *f_c, int n, char c)
{
	int i;
	if (c>='a' && c<='z') {
		i = rand()%4;
		fprintf(f_c, "\ts[%d] = AL%d('%c');\n", n, i, c);
	} else if (c>='0' && c<='9') {
		i = rand()%2;
		fprintf(f_c, "\ts[%d] = NB%d('%c');\n", n, i, c);
	} else if (c==0) {
		i = rand()%4;
		fprintf(f_c, "\ts[%d] = NL%d;\n", n, i);
	} else if (c=='/') {
		i = rand()%2;
		fprintf(f_c, "\ts[%d] = SL%d;\n", n, i);
	} else if (c=='.') {
		fprintf(f_c, "\ts[%d] = DOT;\n", n);
	} else if (c=='*') {
		fprintf(f_c, "\ts[%d] = AST;\n", n);
	} else if (c=='?') {
		fprintf(f_c, "\ts[%d] = QST;\n", n);
	} else {
		fprintf(f_c, "\ts[%d] = '%c';\n", n, c);
	}
}

void emit_multi_str(FILE *f_c, char *a[])
{
	int i;
	for (i=0;a[i]; i++) {
		fprintf(f_c, "%s\n", a[i]);
	}
}

void gen_warning(FILE *f)
{
	fprintf(f, WARNING_MSG);
}

void gen_header_fn(FILE *fp, FILE *f_h)
{
	char str[256];
	char *t1, *t2;

	gen_warning(f_h);

	fprintf(f_h, "#ifndef __%s_H__\n", outname);
	fprintf(f_h, "#define __%s_H__\n\n", outname);

	fseek(fp, 0, SEEK_SET);

	fprintf(f_h, "#if 0 // input table\n");
	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;
		fprintf(f_h, "%s\t%s\n", t1, t2);
	}
	fprintf(f_h, "#endif // input table\n\n");

	// generate data decl
	fseek(fp, 0, SEEK_SET);

	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;
		fprintf(f_h, "extern char %s[%d];\n", t1, strlen(t2)+1);
	}

	fprintf(f_h, "\nextern void %s(void);\n", fn_init_name);
	fprintf(f_h, "\n#endif\n");
	fprintf(f_h, "\n");
}

void gen_decl_fn(FILE *fp, FILE *f_c)
{
	char str[256];
	char *t1, *t2;

	gen_warning(f_c);

	emit_multi_str(f_c, init_def);

	fprintf(f_c, "#include \"%s.h\"\n\n", outname);

	fprintf(f_c, "#define CHK_FN_EN 0\n\n");

	// generate data decl
	fseek(fp, 0, SEEK_SET);
	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;
		fprintf(f_c, "char %s[%d];\n", t1, strlen(t2)+1);
	}
	fprintf(f_c, "\n");
}

void permute(unsigned char idx[], int len)
{
	int i;
	if (len < 2) {
		return;
	}
	for (i=0;i<len;i++)
		idx[i] = i;

	for (i=0;i<len/2;i++) {
		int a,b;
		unsigned char t;
		a = rand()%len;
		b = rand()%len;
		if (a!=b) {
			t = idx[a];
			idx[a] = idx[b];
			idx[b] = t;
		}
	}
}

void gen_fn(FILE *fp, FILE *f_c)
{
	char str[256];
	unsigned char idx[256];
	char *t1, *t2;
	int i;

	// generate data decl
	fseek(fp, 0, SEEK_SET);
	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;

		fprintf(f_c, "static inline void %s_init(char *s)\n{\n\t// \"%s\"\n", t1, t2);
		permute(idx, strlen(t2)+1);	// permute char emit seq including null
		for (i=0;i<strlen(t2)+1;i++) {
			// gen char including NULL
			emit_char(f_c, idx[i], t2[idx[i]]);
		}
		fprintf(f_c, "}\n");
	}
	fprintf(f_c, "\n");
}

char *debug_fn[]={
	"static void _CHK(int idx, char *n, char *s)",
	"{",
		"\tif (strncmp(n,s,strlen(s)+1)==0) {",
			"\t\tprintf(\"[%2d] O [%s]==[%s]\\n\", idx, n, s);",
		"\t} else {",
			"\t\tprintf(\"[%2d] X [%s]!=[%s]\\n\", idx, n, s);",
		"\t}",
	"}",
	NULL
};

void gen_last_fn(FILE *fp, FILE *f_c)
{
	char str[256];
	char *t1, *t2;
	int i=0;

	// gen debugging routine
	fprintf(f_c, "#if CHK_FN_EN\n");
	emit_multi_str(f_c, debug_fn);

	fprintf(f_c, "static void check_fn(void)\n{\n");

	fseek(fp, 0, SEEK_SET);
	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;

		fprintf(f_c, "\t_CHK(%d, %s, \"%s\");\n", i++, t1, t2);
	}
	fprintf(f_c, "}\n");

	fprintf(f_c, "#endif\n");

	fprintf(f_c, "\n");

	fseek(fp, 0, SEEK_SET);

	// gen init fn
	
	fprintf(f_c, "void %s(void)\n{\n", fn_init_name);
	fprintf(f_c, "\n#if CHK_FN_EN\n");
	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;

		fprintf(f_c, "\tmemset(%s, 0xff, sizeof(%s));\n", t1, t1);
	}
	fprintf(f_c, "#endif\n\n");

	fseek(fp, 0, SEEK_SET);

	while (fgets(str, sizeof(str), fp)) {
		t1 = strtok(str, "\r\n \t");
		if (t1) 
			t2 = strtok(NULL, "\r\n \t");
		if (!t1 || !t2)
			continue;
		if (t1[0]=='#')
			continue;

		fprintf(f_c, "\t%s_init(%s);\n", t1, t1);
	}

	fprintf(f_c, "\n#if CHK_FN_EN\n");
	fprintf(f_c, "\tcheck_fn();\n");
	fprintf(f_c, "#endif\n");
	fprintf(f_c, "}\n");
	fprintf(f_c, "\n");
	fprintf(f_c, "#if 0\nint main() {\n\t%s();\n}\n#endif\n", fn_init_name);

}

void gen(FILE *fp, FILE *f_c, FILE *f_h)
{
	gen_header_fn(fp, f_h);	// generate header file
	gen_decl_fn(fp, f_c);	// generate declaration part
	gen_fn(fp, f_c);	// generate functions for each string
	gen_last_fn(fp, f_c);	// generate debug function and init function
}


int main(int argc, char *argv[])
{
	FILE *fp, *f_c, *f_h;
	char str[80];

	if (argc < 3) {
		fprintf(stderr, "Arg err\n");
		return (0);
	}

	if (argc > 3) {
		snprintf(fn_init_name, sizeof(fn_init_name), "%s", argv[3]);
	} else {
		snprintf(fn_init_name, sizeof(fn_init_name), "%s_init", argv[2]);
	}
	fp = fopen(argv[1], "r");
	if (!fp) {
		fprintf(stderr, "cannot open input\n");
		return (0);
	}
	outname = argv[2];
	snprintf(str, sizeof(str), "%s.c", outname);
	f_c = fopen(str, "w");
	if (!f_c) {
		fprintf(stderr, "cannot open output c\n");
		return (0);
	}
	snprintf(str, sizeof(str), "%s.h", outname);
	f_h = fopen(str, "w");
	if (!f_h) {
		fprintf(stderr, "cannot open output h\n");
		return (0);
	}

	srand(time(NULL));

	gen(fp, f_c, f_h);

	fclose(fp);
	fclose(f_c);
	fclose(f_h);
	return 0;
}


