#ifndef __BCM_CFG_API_C__
#define __BCM_CFG_API_C__

#include <stdio.h>
#include <stdlib.h>
#include "parameter_api.h"
#include "bcmnvram.h"
#include "bcm_cfg_api.h"
#include "bcm_param_api.h"
#include "cwmplib.h"

#include <libytool.h>
#ifdef __LGU_PUF__
#include <sec_cli.h>
#endif
//#include "../busybox-1.x/include/libbb.h"

#if 0
#define bcmcfg_debug_printf(dir, fmt, args...)  fprintf(dir, fmt, ##args)
#else
#define bcmcfg_debug_printf(dir, fmt, args...)  while(0) { }
#endif

extern void str_lower(char *p);

char *bcm_event_str_get(int api)
{

	switch(api) {
	case CWMP_DHCPSERVERCONF:
		return "CWMP_DHCPSERVERCONF";
	case CWMP_DHCPSERVERENABLE:
		return "CWMP_DHCPSERVERENABLE";
	case CWMP_DHCPLEASETIME:
		return "CWMP_DHCPLEASETIME";
	case CWMP_WAN_CONN_NUM_ENTRIES:
		return "CWMP_WAN_CONN_NUM_ENTRIES";
	case CWMP_MODEM_FIRMWARE_VER:
		return "CWMP_MODEM_FIRMWARE_VER";
	case CWMP_ENABLED_OPTIONS:
		return "CWMP_ENABLED_OPTIONS";
	case CWMP_ADDITIONAL_HW_VER:
		return "CWMP_ADDITIONAL_HW_VER";
	case CWMP_ADDITIONAL_SW_VER:
		return "CWMP_ADDITIONAL_SW_VER";		
	case CWMP_SPEC_VER:
		return "CWMP_SPEC_VER";
	case CWMP_PROVISIONINGCODE:
		return "CWMP_PROVISIONINGCODE";
	//case CWMP_UPTIME:																					return "CWMP_UPTIME";
	case CWMP_FIRSTUSEDATE:
		return "CWMP_FIRSTUSEDATE";
	case CWMP_DEVICELOG:
		return "CWMP_DEVICELOG";
	case CWMP_VENDOR_CONFIGFILE_NUM_ENTRIES:
		return "CWMP_VENDOR_CONFIGFILE_NUM_ENTRIES";
	case CWMP_LAN_ETHERNET_INTERFACE_NUM_ENTRIES:
		return "CWMP_LAN_ETHERNET_INTERFACE_NUM_ENTRIES";
	case CWMP_LAN_WLAN_CONF_NUM_ENTRIES:
		return "CWMP_LAN_WLAN_CONF_NUM_ENTRIES";
	case CWMP_DEFAULT_CONN_SERVICE:
		return "CWMP_DEFAULT_CONN_SERVICE";
	case CWMP_FORWARD_NUM_ENTRIES:
		return "CWMP_FORWARD_NUM_ENTRIES";
	case CWMP_NTPSERVER1:
		return "CWMP_NTPSERVER1";
	case CWMP_NTPSERVER2:
		return "CWMP_NTPSERVER2";
	case CWMP_NTPSERVER3:
		return "CWMP_NTPSERVER3";
	case CWMP_NTPSERVER4:
		return "CWMP_NTPSERVER4";
	case CWMP_NTPSERVER5:
		return "CWMP_NTPSERVER5";
	case CWMP_CURRENT_LOCALTIME:
		return "CWMP_CURRENT_LOCALTIME";
	case CWMP_LOCALTIMEZONE:
		return "CWMP_LOCALTIMEZONE";
	case CWMP_LOCALTIMEZONENAME:
		return "CWMP_LOCALTIMEZONENAME";
	case CWMP_DAYLIGHT_SAVING_USED:
		return "CWMP_DAYLIGHT_SAVING_USED";
	case CWMP_DAYLIGHT_SAVING_START:
		return "CWMP_DAYLIGHT_SAVING_START";
	case CWMP_DAYLIGHT_SAVING_END:
		return "CWMP_DAYLIGHT_SAVING_END";
	case CWMP_TIME_ENABLE:
		return "CWMP_TIME_ENABLE";
	case CWMP_TIME_STATUS:
		return "CWMP_TIME_STATUS";
	case CWMP_VENDOR_CONFIGFILE_NAME:
		return "CWMP_VENDOR_CONFIGFILE_NAME";
	case CWMP_VENDOR_CONFIGFILE_VER:
		return "CWMP_VENDOR_CONFIGFILE_VER";
	case CWMP_VENDOR_CONFIGFILE_DATE:
		return "CWMP_VENDOR_CONFIGFILE_DATE";
	case CWMP_VENDOR_CONFIGFILE_DESCRIPTION:
		return "CWMP_VENDOR_CONFIGFILE_DESCRIPTION";
	case CWMP_FIRMWARE_VER:
		return "CWMP_FIRMWARE_VER";
	case CWMP_FIRMWARE_PREVER:
		return "CWMP_FIRMWARE_PREVER";
	case CWMP_FIRMWARE_URL:
		return "CWMP_FIRMWARE_URL";
	case CWMP_FIRMWARE_USERNAME:
		return "CWMP_FIRMWARE_USERNAME";
	case CWMP_FIRMWARE_PW:
		return "CWMP_FIRMWARE_PW";
	case CWMP_FIRMWARE_PACKAGE_SIZE:
		return "CWMP_FIRMWARE_PACKAGE_SIZE";
	case CWMP_FIRMWARE_PACKAGE_VER:
		return "CWMP_FIRMWARE_PACKAGE_VER";
	case CWMP_FIRMWARE_PACKAGE_FILENAME:
		return "CWMP_FIRMWARE_PACKAGE_FILENAME";
	case CWMP_FIRMWARE_RESULTCODE:
		return "CWMP_FIRMWARE_RESULTCODE";
	case CWMP_FIRMWARE_RESULT_ERRMSG:
		return "CWMP_FIRMWARE_RESULT_ERRMSG";
	case CWMP_FIRMWARE_LAST_PACKAGE_DOWNLOAD_DATE:
		return "CWMP_FIRMWARE_LAST_PACKAGE_DOWNLOAD_DATE";
	case CWMP_FIRMWARE_LAST_UPGRADE_DATE:
		return "CWMP_FIRMWARE_LAST_UPGRADE_DATE";
	case CWMP_FIRMWARE_CONTROL_TRAFFIC:
		return "CWMP_FIRMWARE_CONTROL_TRAFFIC";
	case CWMP_FIRMWARE_DOWNLOAD_RETRIES:
		return "CWMP_FIRMWARE_DOWNLOAD_RETRIES";
	case CWMP_FIRMWARE_DOWNLOAD_TIMEOUT:
		return "CWMP_FIRMWARE_DOWNLOAD_TIMEOUT";
	case CWMP_HOST:
		return "CWMP_HOST";
	case CWMP_MONTIME:
		return "CWMP_MONTIME";
	case CWMP_MONRANGE:
		return "CWMP_MONRANGE";
	case CWMP_MONDAYS:
		return "CWMP_MONDAYS";
	case CWMP_MONPERIOD:
		return "CWMP_MONPERIOD";															
	case CWMP_BASIC_INFO_ENABLE:
		return "CWMP_BASIC_INFO_ENABLE";
	case CWMP_CONFIG_INFO_ENABLE:
		return "CWMP_CONFIG_INFO_ENABLE";
	case CWMP_WLAN_INFO_ENABLE:
		return "CWMP_WLAN_INFO_ENABLE";
	case CWMP_QOS_INFO_ENABLE:
		return "CWMP_QOS_INFO_ENABLE";
	case CWMP_SERVER_INFO_ENABLE:
		return "CWMP_SERVER_INFO_ENABLE";
	case CWMP_MON_INFO_ENABLE:
		return "CWMP_MON_INFO_ENABLE";
	case CWMP_ACL_INFO_ENABLE:
		return "CWMP_ACL_INFO_ENABLE";
	case CWMP_WLAN_NUM_ENTRIES:
		return "CWMP_WLAN_NUM_ENTRIES";
	case CWMP_LAN_USB_INTERFACE_NUM_ENTRIES:
		return "CWMP_LAN_USB_INTERFACE_NUM_ENTRIES";
	case CWMP_FLAG:
		return "CWMP_FLAG";
	case CWMP_CERT_PASSWORD:
		return "CWMP_CERT_PASSWORD";
	case CWMP_RB_COMMANDKEY:
		return "CWMP_RB_COMMANDKEY";
	case CWMP_DL_COMMANDKEY:
		return "CWMP_DL_COMMANDKEY";
	case CWMP_DL_STARTTIME:
		return "CWMP_DL_STARTTIME";
	case CWMP_DL_COMPLETETIME:
		return "CWMP_DL_COMPLETETIME";
	case CWMP_DL_FAULTCODE:
		return "CWMP_DL_FAULTCODE";
	case CWMP_INFORM_EVENTCODE:
		return "CWMP_INFORM_EVENTCODE";
	case CWMP_ACS_URL:
		return "CWMP_ACS_URL";
	case CWMP_ACS_USERNAME:
		return "CWMP_ACS_USERNAME";
	case CWMP_ACS_PASSWORD:
		return "CWMP_ACS_PASSWORD";
	case CWMP_CPE_SERVER_PORT:
		return "CWMP_CPE_SERVER_PORT";
	case CWMP_CONREQ_USERNAME:
		return "CWMP_CONREQ_USERNAME";
	case CWMP_CONREQ_PASSWORD:
		return "CWMP_CONREQ_PASSWORD";
	case CWMP_INFORM_ENABLE:
		return "CWMP_INFORM_ENABLE";
	case CWMP_INFORM_INTERVAL:
		return "CWMP_INFORM_INTERVAL";
	case CWMP_INFORM_TIME:
		return "CWMP_INFORM_TIME";
	case CWMP_ACS_UPGRADESMANAGED:
		return "CWMP_ACS_UPGRADESMANAGED";
	case CWMP_RADIUS_ACC_IPADDRESS:
		return "CWMP_RADIUS_ACC_IPADDRESS";
	case CWMP_RADIUS_ACC_PORT:
		return "CWMP_RADIUS_ACC_PORT";
	case CWMP_RADIUS_AUTH_IPADDRESS:
		return "CWMP_RADIUS_ACC_IPADDRESS";
	case CWMP_RADIUS_AUTH_PORT:
		return "CWMP_RADIUS_ACC_PORT";
	case CWMP_TELNET_ACCESSLIST_IPADDRESS:
		return "CWMP_TELNET_ACCESSLIST_IPADDRESS";
	case CWMP_TELNET_ACCESSLIST_PORT:
		return "CWMP_TELNET_ACCESSLIST_PORT";
	case CWMP_QMS_IPADDRESS:
		return "CWMP_QMS_IPADDRESS";
	case CWMP_QMS_PORT1:
		return "CWMP_QMS_PORT1";
	case CWMP_QMS_PORT2:
		return "CWMP_QMS_PORT2";
	case CWMP_WEBMNGMT_SERVER_ENABLE:
		return "CWMP_WEBMNGMT_SERVER_ENABLE";
	case CWMP_WEBMNGMT_SERVER_LOGIN_IPADDR:
		return "CWMP_WEBMNGMT_SERVER_LOGIN_IPADDR";
	case CWMP_WEBMNGMT_SERVER_LOGIN_PORT:
		return "CWMP_WEBMNGMT_SERVER_LOGIN_PORT";
	case CWMP_WEBMNGMT_SERVER_LOGINKEY:
		return "CWMP_WEBMNGMT_SERVER_LOGINKEY";
	case CWMP_WS_IPADDR:
		return "CWMP_WS_IPADDR";
	case CWMP_WS_PORT:
		return "CWMP_WS_PORT";
	case CWMP_ATCLIST_IPADDR:
		return "CWMP_ATCLIST_IPADDR";
	case CWMP_FORWARDING_ENABLE:
		return "CWMP_FORWARDING_ENABLE";
	case CWMP_FORWARDING_STATUS:
		return "CWMP_FORWARDING_STATUS";
	case CWMP_FORWARDING_TYPE:
		return "CWMP_FORWARDING_TYPE";
	case CWMP_FORWARDING_DEST_IPADDR:
		return "CWMP_FORWARDING_DEST_IPADDR";
	case CWMP_FORWARDING_DEST_SUBNETMASK:
		return "CWMP_FORWARDING_DEST_SUBNETMASK";
	case CWMP_FORWARDING_SRC_IPADDR:
		return "CWMP_FORWARDING_SRC_IPADDR";
	case CWMP_FORWARDING_SRC_SUBNETMASK:
		return "CWMP_FORWARDING_SRC_SUBNETMASK";
	case CWMP_FORWARDING_GATEWAY_IPADDR:
		return "CWMP_FORWARDING_GATEWAY_IPADDR";
	case CWMP_FORWARDING_INTERFACE:
		return "CWMP_FORWARDING_INTERFACE";
	case CWMP_FORWARDING_METRIC:
		return "CWMP_FORWARDING_METRIC";
	case CWMP_FORWARDING_MTU:
		return "CWMP_FORWARDING_MTU";
	case CWMP_FORWARDING_POLICY:
		return "CWMP_FORWARDING_POLICY";
	case CWMP_FORWARDING_STATIC_ROUTE:
		return "CWMP_FORWARDING_STATIC_ROUTE";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_ENABLE:
		return "CWMP_LAN_ETHERNET_INTERFACE_CONF_ENABLE";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_STATUS:
		return "CWMP_LAN_ETHERNET_INTERFACE_CONF_STATUS";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC:
		return "CWMP_LAN_ETHERNET_INTERFACE_CONF_MACADDR";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC_CONTROL_ENABLE:
		return "CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC_CONTROL_ENABLE";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAXBITRATE:
		return "CWMP_MAXBITRATE";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE:
		return "CWMP_DUPLEXMODE";
	case CWMP_LAN_ETHERNET_INTERFACE_CONF_NAME:
		return "CWMP_LAN_ETHERNET_INTERFACE_CONF_NAME";
	case CWMP_WLAN_CONF_ENABLE:
		return "CWMP_WLAN_CONF_ENABLE";
	case CWMP_WLAN_CONF_STATUS:
		return "CWMP_WLAN_CONF_STATUS";
	case CWMP_WLAN_CONF_BSSID:
		return "CWMP_WLAN_CONF_BSSID";
	case CWMP_WLAN_CONF_MAXBITRATE:
		return "CWMP_WLAN_CONF_MAXBITRATE";
	case CWMP_WLAN_CONF_CHANNEL:
		return "CWMP_WLAN_CONF_CHANNEL";
	case CWMP_WLAN_CONF_SSID:
		return "CWMP_WLAN_CONF_SSID";
	case CWMP_WLAN_CONF_BEACONTYPE:
		return "CWMP_WLAN_CONF_BEACONTYPE";
	case CWMP_WLAN_CONF_MAC_CONTROL_ENABLE:
		return "CWMP_WLAN_CONF_MAC_CONTROL_ENABLE";
	case CWMP_WLAN_CONF_STANDARD:
		return "CWMP_WLAN_CONF_STANDARD";
	case CWMP_WLAN_CONF_WEP_KEYINDEX:
		return "CWMP_WLAN_CONF_WEP_KEYINDEX";
	case CWMP_WLAN_CONF_KEY_PASSPHRASE:
		return "CWMP_WLAN_CONF_KEY_PASSPHRASE";
	case CWMP_WLAN_CONF_WEP_ENCRYPT_LEVEL:
		return "CWMP_WLAN_CONF_WEP_ENCRYPT_LEVEL";
	case CWMP_WLAN_CONF_BASIC_ENCRYPT_MODES:
		return "CWMP_WLAN_CONF_BASIC_ENCRYPT_MODES";
	case CWMP_WLAN_CONF_BASIC_AUTH_MODE:
		return "CWMP_WLAN_CONF_BASIC_AUTH_MODE";
	case CWMP_WLAN_CONF_WPA_ENCRYPT_MODES:
		return "CWMP_WLAN_CONF_WPA_ENCRYPT_MODES";
	case CWMP_WLAN_CONF_WPA_AUTH_MODE:
		return "CWMP_WLAN_CONF_WPA_AUTH_MODE";
	case CWMP_WLAN_CONF_IEEE11I_ENCTYPT_MODES:
		return "CWMP_WLAN_CONF_IEEE11I_ENCTYPT_MODES";
	case CWMP_WLAN_CONF_IEEE11I_AUTH_MODES:
		return "CWMP_WLAN_CONF_IEEE11I_AUTH_MODES";
	case CWMP_WLAN_CONF_POSSIBLE_CHANNELS:
		return "CWMP_WLAN_CONF_POSSIBLE_CHANNELS";
	case CWMP_WLAN_CONF_BASIC_DATA_TRANSMIT_RATES:
		return "CWMP_WLAN_CONF_BASIC_DATA_TRANSMIT_RATES";
	case CWMP_WLAN_CONF_OPERATION_DATA_TRANSMIT_RATES:
		return "CWMP_WLAN_CONF_OPERATION_DATA_TRANSMIT_RATES";
	case CWMP_WLAN_CONF_POSSIBLE_DATA_TRANSMIT_RATES:
		return "CWMP_WLAN_CONF_POSSIBLE_DATA_TRANSMIT_RATES";
	case CWMP_WLAN_CONF_INSECURE_OOB_ACCESS_ENABLED:
		return "CWMP_WLAN_CONF_INSECURE_OOB_ACCESS_ENABLED";
	case CWMP_WLAN_CONF_BEACON_ADVERTISE_ENABLED:
		return "CWMP_WLAN_CONF_BEACON_ADVERTISE_ENABLED";
	case CWMP_WLAN_CONF_RADIO_ENABLED:
		return "CWMP_WLAN_CONF_RADIO_ENABLED";
	case CWMP_WLAN_CONF_ARF_ENABLED:
		return "CWMP_WLAN_CONF_ARF_ENABLED";
	case CWMP_WLAN_CONF_LOCATION_DESCRIPTION:
		return "CWMP_WLAN_CONF_LOCATION_DESCRIPTION";
	case CWMP_WLAN_CONF_REGULATORY_DOMAIN:
		return "CWMP_WLAN_CONF_REGULATORY_DOMAIN";
	case CWMP_WLAN_CONF_TOTAL_PSK_FAILURES:
		return "CWMP_WLAN_CONF_TOTAL_PSK_FAILURES";
	case CWMP_WLAN_CONF_TOTAL_INTEGRITY_FAILURES:
		return "CWMP_WLAN_CONF_TOTAL_INTEGRITY_FAILURES";
	case CWMP_WLAN_CONF_CHANNEL_IN_USE:
		return "CWMP_WLAN_CONF_CHANNEL_IN_USE";
	case CWMP_WLAN_CONF_DEVICE_OPERATION_MODE:
		return "CWMP_WLAN_CONF_DEVICE_OPERATION_MODE";
	case CWMP_WLAN_CONF_DISTANCE_FROM_ROOT:
		return "CWMP_WLAN_CONF_DISTANCE_FROM_ROOT";
	case CWMP_WLAN_CONF_PEER_BSSID:
		return "CWMP_WLAN_CONF_PEER_BSSID";
	case CWMP_WLAN_CONF_AUTH_SERVICE_MODE:
		return "CWMP_WLAN_CONF_AUTH_SERVICE_MODE";
	case CWMP_WLAN_CONF_TOTAL_BYTES_SENT:
		return "CWMP_WLAN_CONF_TOTAL_BYTES_SENT";
	case CWMP_WLAN_CONF_TOTAL_BYTES_RECEIVED:
		return "CWMP_WLAN_CONF_TOTAL_BYTES_RECEIVED";
	case CWMP_WLAN_CONF_TOTAL_PACKETS_SENT:
		return "CWMP_WLAN_CONF_TOTAL_PACKETS_SENT";
	case CWMP_WLAN_CONF_TOTAL_PACKETS_RECEIVED:
		return "CWMP_WLAN_CONF_TOTAL_PACKETS_RECEIVED";
	case CWMP_WLAN_CONF_TOTAL_ASSOCIATIONS:
		return "CWMP_WLAN_CONF_TOTAL_ASSOCIATIONS";
	case CWMP_WLAN_CONF_NAME:
		return "CWMP_WLAN_CONF_NAME";
	case CWMP_WLAN_CONF_AUTO_CHANNEL_ENABLE:
		return "CWMP_WLAN_CONF_AUTO_CHANNEL_ENABLE";
	case CWMP_WLAN_CONF_SSID_ADVERTISE_ENABLED:
		return "CWMP_WLAN_CONF_SSID_ADVERTISE_ENABLED";
	case CWMP_WLAN_CONF_TRANSMIT_POWER_SUPPORTED:
		return "CWMP_WLAN_CONF_TRANSMIT_POWER_SUPPORTED";
	case CWMP_WLAN_CONF_TRANSMIT_POWER:
		return "CWMP_WLAN_CONF_TRANSMIT_POWER";
	case CWMP_WLAN_CONF_WMM_SUPPORTED:
		return "CWMP_WLAN_CONF_WMM_SUPPORTED";
	case CWMP_WLAN_CONF_UAPSD_SUPPORTED:
		return "CWMP_WLAN_CONF_UAPSD_SUPPORTED";
	case CWMP_WLAN_CONF_WMM_ENABLE:
		return "CWMP_WLAN_CONF_WMM_ENABLE";
	case CWMP_WLAN_CONF_UAPSD_ENABLE:
		return "CWMP_WLAN_CONF_UAPSD_ENABLE";
	case CWMP_AP_WMM_PARAMETER_NUM_ENTRIES:
		return "CWMP_AP_WMM_PARAMETER_NUM_ENTRIES";
	case CWMP_STA_WMM_PARAMETER_NUM_ENTRIES:
		return "CWMP_STA_WMM_PARAMETER_NUM_ENTRIES";
	case CWMP_HOST_NUM_ENTRIES:
		return "CWMP_HOST_NUM_ENTRIES";
	case CWMP_ENABLED_INTERNET:
		return "CWMP_ENABLED_INTERNET";
	case CWMP_WAN_ACCESSTYPE:
		return "CWMP_WAN_ACCESSTYPE";
	case CWMP_LAYER1_UPSTREAM_MAXBITRATE:
		return "CWMP_LAYER1_UPSTREAM_MAXBITRATE";
	case CWMP_LAYER1_DOWNSTREAM_MAXBITRATE:
		return "CWMP_LAYER1_DOWNSTREAM_MAXBITRATE";
	case CWMP_PHYSICAL_LINK_STATUS:
		return "CWMP_PHYSICAL_LINK_STATUS";
	case CWMP_WAN_ACCESS_PROVIDER:
		return "CWMP_WAN_ACCESS_PROVIDER";
	case CWMP_WAN_TOTAL_BYTES_SENT:
		return "CWMP_WAN_TOTAL_BYTES_SENT";
	case CWMP_WAN_TOTAL_BYTES_RECEIVED:
		return "CWMP_WAN_TOTAL_BYTES_RECEIVED";
	case CWMP_WAN_TOTAL_PACKETS_SENT:
		return "CWMP_WAN_TOTAL_PACKETS_SENT";
	case CWMP_WAN_TOTAL_PACKETS_RECEIVED:
		return "CWMP_WAN_TOTAL_PACKETS_RECEIVED";
	case CWMP_WAN_MAX_ACTIVE_CONN:
		return "CWMP_WAN_MAX_ACTIVE_CONN";
	case CWMP_WAN_NUM_ACTIVE_CONN:
		return "CWMP_WAN_NUM_ACTIVE_CONN";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_ENABLE:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_ENABLE";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_STATUS:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_STATUS";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_MAC:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_MAC";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_MAXBITRATE:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_MAXBITRATE";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPINGRATE:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPINGRATE";
	case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPING_BURSTSIZE:
		return "CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPING_BURSTSIZE";
	case CWMP_WAN_IP_CONN_NUM_ENTRIES:
		return "CWMP_WAN_IP_CONN_NUM_ENTRIES";
	case CWMP_WLAN_SSID_TX_OVER_ENABLE:
		return "CWMP_WLAN_SSID_TX_OVER_ENABLE";
	case CWMP_WLAN_SSID_RX_OVER_ENABLE:
		return "CWMP_WLAN_SSID_RX_OVER_ENABLE";
	case CWMP_WLAN_SSID_CONN_OVER_ENABLE:
		return "CWMP_WLAN_SSID_CONN_OVER_ENABLE";
	case CWMP_IP_INTERFACE_ENABLE:
		return "CWMP_IP_INTERFACE_ENABLE";
	case CWMP_IP_INTERFACE_IPADDR:
		return "CWMP_IP_INTERFACE_IPADDR";
	case CWMP_IP_INTERFACE_SUBNETMASK:
		return "CWMP_IP_INTERFACE_SUBNETMASK";
	case CWMP_IP_INTERFACE_ADDRTYPE:
		return "CWMP_IP_INTERFACE_ADDRTYPE";
	case CWMP_STATS_BYTES_SENT:
		return "CWMP_STATS_BYTES_SENT";
	case CWMP_STATS_BYTES_RECEIVED:
		return "CWMP_STATS_BYTES_RECEIVED";
	case CWMP_STATS_PACKETS_SENT:
		return "CWMP_STATS_PACKETS_SENT";
	case CWMP_STATS_PACKETS_RECEIVED:
		return "CWMP_STATS_PACKETS_RECEIVED";
	case CWMP_STATS_ERRORS_SENT:
		return "CWMP_STATS_ERRORS_SENT";
	case CWMP_STATS_ERRORS_RECEIVED:
		return "CWMP_STATS_ERRORS_RECEIVED";
	case CWMP_STATS_UNICAST_PACKETS_SENT:
		return "CWMP_STATS_UNICAST_PACKETS_SENT";
	case CWMP_STATS_UNICAST_PACKETS_RECEIVED:
		return "CWMP_STATS_UNICAST_PACKETS_RECEIVED";
	case CWMP_STATS_DISCARD_PACKETS_SENT:
		return "CWMP_STATS_DISCARD_PACKETS_SENT";
	case CWMP_STATS_DISCARD_PACKETS_RECEIVED:
		return "CWMP_STATS_DISCARD_PACKETS_RECEIVED";
	case CWMP_STATS_MULTICAST_PACKETS_SENT:
		return "CWMP_STATS_MULTICAST_PACKETS_SENT";
	case CWMP_STATS_MULTICAST_PACKETS_RECEIVED:
		return "CWMP_STATS_MULTICAST_PACKETS_RECEIVED";
	case CWMP_STATS_BROADCAST_PACKETS_SENT:
		return "CWMP_STATS_BROADCAST_PACKETS_SENT";
	case CWMP_STATS_BROADCAST_PACKETS_RECEIVED:
		return "CWMP_STATS_BROADCAST_PACKETS_RECEIVED";
	case CWMP_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED:
		return "CWMP_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED";
	case CWMP_WPS_ENABLE:
		return "CWMP_WPS_ENABLE";
	case CWMP_WPS_DEVICENAME:
		return "CWMP_WPS_DEVICENAME";
	case CWMP_WPS_DEVICEPW:
		return "CWMP_WPS_DEVICEPW";
	case CWMP_HOST_IPADDR:
		return "CWMP_HOST_IPADDR";
	case CWMP_HOST_ADDR_SOURCE:
		return "CWMP_HOST_ADDR_SOURCE";
	case CWMP_HOST_LEASE_TIME_REMAINING:
		return "CWMP_HOST_LEASE_TIME_REMAINING";
	case CWMP_HOST_MACADDR:
		return "CWMP_HOST_MACADDR";
	case CWMP_HOST_NAME:
		return "CWMP_HOST_NAME";
	case CWMP_HOST_INTERFACETYPE:
		return "CWMP_HOST_INTERFACETYPE";
	case CWMP_HOST_ACTIVE:
		return "CWMP_HOST_ACTIVE";
	case CWMP_HOST_LAYER2INTERFACE:
		return "CWMP_HOST_LAYER2INTERFACE";
	case CWMP_HOST_VENDORCLASSID:
		return "CWMP_HOST_VENDORCLASSID";
	case CWMP_HOST_CLIENTID:
		return "CWMP_HOST_CLIENTID";
	case CWMP_HOST_USERCLASSID:
		return "CWMP_HOST_USERCLASSID";
	case CWMP_CONNECTION_ACTIVE_CONN_DEVICE_CONTAINER:
		return "CWMP_CONNECTION_ACTIVE_CONN_DEVICE_CONTAINER";
	case CWMP_CONNECTION_ACTIVE_CONN_SERVICEID:
		return "CWMP_CONNECTION_ACTIVE_CONN_SERVICEID";
	case CWMP_ASSOC_DEVICE_MACADDR:
		return "CWMP_ASSOC_DEVICE_MACADDR";
	case CWMP_ASSOC_DEVICE_IPADDR:
		return "CWMP_ASSOC_DEVICE_IPADDR";
	case CWMP_ASSOC_DEVICE_AUTHSTATE:
		return "CWMP_ASSOC_DEVICE_AUTHSTATE";
	case CWMP_ASSOC_DEVICE_LAST_REQ_UNICAST_CIPHER:
		return "CWMP_ASSOC_DEVICE_LAST_REQ_UNICAST_CIPHER";
	case CWMP_ASSOC_DEVICE_LAST_REQ_MULTICAST_CIPHER:
		return "CWMP_ASSOC_DEVICE_LAST_REQ_MULTICAST_CIPHER";
	case CWMP_ASSOC_DEVICE_LAST_PMKLD:
		return "CWMP_ASSOC_DEVICE_LAST_PMKLD";
	case CWMP_ASSOC_DEVICE_LAST_DATA_TRANSMIT_RATE:
		return "CWMP_ASSOC_DEVICE_LAST_DATA_TRANSMIT_RATE";
	case CWMP_WAN_ETHERNET_LINK_STATUS:
		return "CWMP_WAN_ETHERNET_LINK_STATUS";
	case CWMP_VLAN_ENABLE:
		return "CWMP_VLAN_ENABLE";
	case CWMP_VLAN_NAME:
		return "CWMP_VLAN_NAME";
	case CWMP_VLAN_ID:
		return "CWMP_VLAN_ID";
	case CWMP_WAN_IP_ENABLE:
		return "CWMP_WAN_IP_ENABLE";
	case CWMP_WAN_IP_CONN_TYPE:
		return "CWMP_WAN_IP_CONN_TYPE";
	case CWMP_WAN_IP_CONN_NAME:
		return "CWMP_WAN_IP_CONN_NAME";
	case CWMP_WAN_IP_CONN_AUTO_DISCONN_TIME:
		return "CWMP_WAN_IP_CONN_AUTO_DISCONN_TIME";
	case CWMP_WAN_IP_CONN_IDLE_DISCONN_TIME:
		return "CWMP_WAN_IP_CONN_IDLE_DISCONN_TIME";
	case CWMP_WAN_IP_CONN_WARN_DISCONN_DELAY:
		return "CWMP_WAN_IP_CONN_WARN_DISCONN_DELAY";
	case CWMP_WAN_IP_CONN_NAT_ENABLED:
		return "CWMP_WAN_IP_CONN_NAT_ENABLED";
	case CWMP_WAN_IP_CONN_ADDRESSING_TYPE:
		return "CWMP_WAN_IP_CONN_ADDRESSING_TYPE";
	case CWMP_WAN_IP_CONN_EXTERNAL_IPADDR:
		return "CWMP_WAN_IP_CONN_EXTERNAL_IPADDR";
	case CWMP_WAN_IP_CONN_SUBNETMASK:
		return "CWMP_WAN_IP_CONN_SUBNETMASK";
	case CWMP_WAN_IP_CONN_DEFAULT_GW:
		return "CWMP_WAN_IP_CONN_DEFAULT_GW";
	case CWMP_WAN_IP_CONN_DNS_ENABLED:
		return "CWMP_WAN_IP_CONN_DNS_ENABLED";
	case CWMP_WAN_IP_CONN_DNS_OVERRIDE_ALLOWED:
		return "CWMP_WAN_IP_CONN_DNS_OVERRIDE_ALLOWED";
	case CWMP_WAN_IP_CONN_DNS_SERVERS:
		return "CWMP_WAN_IP_CONN_DNS_SERVERS";
	case CWMP_WAN_IP_CONN_MAX_MTUSIZE:
		return "CWMP_WAN_IP_CONN_MAX_MTUSIZE";
	case CWMP_WAN_IP_CONN_MACADDR:
		return "CWMP_WAN_IP_CONN_MACADDR";
	case CWMP_WAN_IP_CONN_MACADDR_OVERRIDE:
		return "CWMP_WAN_IP_CONN_MACADDR_OVERRIDE";
	case CWMP_WAN_IP_CONN_ROUTER_PROTOCOL_RX:
		return "CWMP_WAN_IP_CONN_ROUTER_PROTOCOL_RX";
	case CWMP_WAN_IP_CONN_SHAPING_RATE:
		return "CWMP_WAN_IP_CONN_SHAPING_RATE";
	case CWMP_WAN_IP_CONN_SHAPING_BURST_SIZE:
		return "CWMP_WAN_IP_CONN_SHAPING_BURST_SIZE";
	case CWMP_WAN_IP_CONN_RESET:
		return "CWMP_WAN_IP_CONN_RESET";
	case CWMP_WAN_IP_CONN_ENABLE:
		return "CWMP_WAN_IP_CONN_ENABLE";
	case CWMP_WAN_IP_CONN_POSSIBLE_CONN_TYPE:
		return "CWMP_WAN_IP_CONN_POSSIBLE_CONN_TYPE";
	case CWMP_WAN_IP_CONN_UPTIME:
		return "CWMP_WAN_IP_CONN_UPTIME";
	case CWMP_WAN_IP_CONN_LAST_CONN_ERROR:
		return "CWMP_WAN_IP_CONN_LAST_CONN_ERROR";
	case CWMP_WAN_IP_CONN_RSIP_AVAILABLE:
		return "CWMP_WAN_IP_CONN_RSIP_AVAILABLE";
	case CWMP_WAN_IP_CONN_PORTMAPPING_NUM_ENTRIES:
		return "CWMP_WAN_IP_CONN_PORTMAPPING_NUM_ENTRIES";
	case CWMP_LIST_URL:
		return "CWMP_LIST_URL";
	case CWMP_DMZ_ENABLE:
		return "CWMP_DMZ_ENABLE";
	case CWMP_DMZ_IP_ADDR:
		return "CWMP_DMZ_IP_ADDR";
	case CWMP_DMZ_IP_MACADDR:
		return "CWMP_DMZ_IP_MACADDR";
	case CWMP_ETHERNET_STATS_BYTES_SENT:
		return "CWMP_ETHERNET_STATS_BYTES_SENT";
	case CWMP_ETHERNET_STATS_BYTES_RECEIVED:
		return "CWMP_ETHERNET_STATS_BYTES_RECEIVED";
	case CWMP_ETHERNET_STATS_PACKETS_SENT:
		return "CWMP_ETHERNET_STATS_PACKETS_SENT";
	case CWMP_ETHERNET_STATS_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_PACKETS_RECEIVED";
	case CWMP_ETHERNET_STATS_ERRORS_SENT:
		return "CWMP_ETHERNET_STATS_ERRORS_SENT";
	case CWMP_ETHERNET_STATS_ERRORS_RECEIVED:
		return "CWMP_ETHERNET_STATS_ERRORS_RECEIVED";
	case CWMP_ETHERNET_STATS_UNICAST_PACKETS_SENT:
		return "CWMP_ETHERNET_STATS_UNICAST_PACKETS_SENT";
	case CWMP_ETHERNET_STATS_UNICAST_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_UNICAST_PACKETS_RECEIVED";
	case CWMP_ETHERNET_STATS_DISCARD_PACKETS_SENT:
		return "CWMP_ETHERNET_STATS_DISCARD_PACKETS_SENT";
	case CWMP_ETHERNET_STATS_DISCARD_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_DISCARD_PACKETS_RECEIVED";
	case CWMP_ETHERNET_STATS_MULTICAST_PACKETS_SENT:
		return "CWMP_ETHERNET_STATS_MULTICAST_PACKETS_SENT";
	case CWMP_ETHERNET_STATS_MULTICAST_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_MULTICAST_PACKETS_RECEIVED";
	case CWMP_ETHERNET_STATS_BROADCAST_PACKETS_SENT:
		return "CWMP_ETHERNET_STATS_BROADCAST_PACKETS_SENT";
	case CWMP_ETHERNET_STATS_BROADCAST_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_BROADCAST_PACKETS_RECEIVED";
	case CWMP_ETHERNET_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED:
		return "CWMP_ETHERNET_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED";
	case CWMP_PORT_MAPPING_ENABLED:
		return "CWMP_PORT_MAPPING_ENABLED";
	case CWMP_PORT_MAPPING_LEASE_DURATION:
		return "CWMP_PORT_MAPPING_LEASE_DURATION";
	case CWMP_PORT_MAPPING_REMOTE_HOST:
		return "CWMP_PORT_MAPPING_REMOTE_HOST";
	case CWMP_PORT_MAPPING_EXTERNAL_PORT:
		return "CWMP_PORT_MAPPING_EXTERNAL_PORT";
	case CWMP_PORT_MAPPING_INTERNAL_PORT:
		return "CWMP_PORT_MAPPING_INTERNAL_PORT";
	case CWMP_PORT_MAPPING_PROTOCOL:
		return "CWMP_PORT_MAPPING_PROTOCOL";
	case CWMP_PORT_MAPPING_INTERNAL_CLIENT:
		return "CWMP_PORT_MAPPING_INTERNAL_CLIENT";
	case CWMP_PORT_MAPPING_DESCRIPTION:
		return "CWMP_PORT_MAPPING_DESCRIPTION";
	case CWMP_PORT_MAPPING_EXTERNAL_PORT_END_RANGE:
		return "CWMP_PORT_MAPPING_EXTERNAL_PORT_END_RANGE";
	case CWMP_PORT_MAPPING_POLICY_ENABLED:
		return "CWMP_PORT_MAPPING_POLICY_ENABLED";
	case CWMP_PORT_MAPPING_POLICY_PROTOCOL:
		return "CWMP_PORT_MAPPING_POLICY_PROTOCOL";
	case CWMP_PORT_MAPPING_POLICY_EXTERNAL_PORT:
		return "CWMP_PORT_MAPPING_POLICY_EXTERNAL_PORT";
	case CWMP_PORT_MAPPING_POLICY_INTERNAL_PORT:
		return "CWMP_PORT_MAPPING_POLICY_INTERNAL_PORT";
	case CWMP_PORT_MAPPING_POLICY_NAME:
		return "CWMP_PORT_MAPPING_POLICY_NAME";
	case CWMP_PORT_MAPPING_POLICY_DEVICETYPE:
		return "CWMP_PORT_MAPPING_POLICY_DEVICETYPE";
	case CWMP_PORT_MAPPING_POLICY_DEVICENUM:
		return "CWMP_PORT_MAPPING_POLICY_DEVICENUM";
	default:
		break;
	}

	return "Unkown Event";
}

int bcm_cfg_get( int api, void *ptr, int ptr_size)
{
	char buf[128] = "", tmp[128] = "";

	if( (ptr == NULL) || (ptr_size == 0)) {
		return 0;
	}

	/* buffer clear */
	memset((char*)ptr, 0, ptr_size);

	switch(api) {
		case CWMP_PORT_MAPPING_POLICY_ENABLED:
			break;
		case CWMP_PORT_MAPPING_POLICY_PROTOCOL:
			break;
		case CWMP_PORT_MAPPING_POLICY_EXTERNAL_PORT:		
			break;
		case CWMP_PORT_MAPPING_POLICY_INTERNAL_PORT:	
			break;
		case CWMP_PORT_MAPPING_POLICY_NAME:					
			break;
		case CWMP_PORT_MAPPING_POLICY_DEVICETYPE:			
			break;
		case CWMP_PORT_MAPPING_POLICY_DEVICENUM:								
			break;
		case CWMP_PORT_MAPPING_ENABLED:						
			break;
		case CWMP_PORT_MAPPING_LEASE_DURATION:
			break;
		case CWMP_PORT_MAPPING_REMOTE_HOST:
			break;
		case CWMP_PORT_MAPPING_EXTERNAL_PORT:
			break;
		case CWMP_PORT_MAPPING_INTERNAL_PORT:
			break;
		case CWMP_PORT_MAPPING_PROTOCOL:
			break;
		case CWMP_PORT_MAPPING_INTERNAL_CLIENT:
			break;
		case CWMP_PORT_MAPPING_DESCRIPTION:
			break;
		case CWMP_PORT_MAPPING_EXTERNAL_PORT_END_RANGE:
			break;
		case CWMP_ETHERNET_STATS_BYTES_SENT:
			break;
		case CWMP_ETHERNET_STATS_BYTES_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_PACKETS_SENT:	
			break;
		case CWMP_ETHERNET_STATS_PACKETS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_ERRORS_SENT:	
			break;
		case CWMP_ETHERNET_STATS_ERRORS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_UNICAST_PACKETS_SENT:
			break;
		case CWMP_ETHERNET_STATS_UNICAST_PACKETS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_DISCARD_PACKETS_SENT:
			break;
		case CWMP_ETHERNET_STATS_DISCARD_PACKETS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_MULTICAST_PACKETS_SENT:
			break;
		case CWMP_ETHERNET_STATS_MULTICAST_PACKETS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_BROADCAST_PACKETS_SENT:
			break;
		case CWMP_ETHERNET_STATS_BROADCAST_PACKETS_RECEIVED:
			break;
		case CWMP_ETHERNET_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED:
			break;
		case CWMP_DMZ_ENABLE:
			break;
		case CWMP_DMZ_IP_ADDR:
			break;
		case CWMP_DMZ_IP_MACADDR:
			break;
		case CWMP_LIST_URL:
			break;
		case CWMP_WAN_IP_ENABLE:
			break;
		case CWMP_WAN_IP_CONN_TYPE:
			break;
		case CWMP_WAN_IP_CONN_NAME:	
			break;
		case CWMP_WAN_IP_CONN_AUTO_DISCONN_TIME:	
			break;
		case CWMP_WAN_IP_CONN_IDLE_DISCONN_TIME:		
			break;
		case CWMP_WAN_IP_CONN_WARN_DISCONN_DELAY:	
			break;
		case CWMP_WAN_IP_CONN_NAT_ENABLED:	
			break;
		case CWMP_WAN_IP_CONN_ADDRESSING_TYPE:
			{
				char *rslt = (char *)ptr;
				if (!IS_BRIDGE_MODE) {
					char buf[32];
					int wan_proto = 0;

					nvram_safe_get_r("WAN_DHCP", buf, sizeof(buf));

					wan_proto = atoi(buf);

					//protocol, 0 - fixed ip, 1 - dhcp client, 3 - PPPoE, 4 - PPTP, 6 - L2TP 
					switch (wan_proto) {
						case 0:
							strncpy(rslt, "Static", 6);
							rslt[6] = '\0';
							break;

						case 1:	
							strncpy(rslt, "DHCP", 4);
							rslt[4] = '\0';
							break;

						case 3:	
							strncpy(rslt, "PPPoE", 5);
							rslt[5] = '\0';
							break;

						default:	
							rslt[0] = 0;
							break;
					}				/* -----  end switch  ----- */
				} else 
					rslt[0] = 0;
			}
			break;
		case CWMP_WAN_IP_CONN_EXTERNAL_IPADDR:
			get_wanip((char *)ptr, ptr_size);
			break;
		case CWMP_WAN_IP_CONN_SUBNETMASK:
			get_wanmask((char *)ptr, ptr_size);
			break;
		case CWMP_WAN_IP_CONN_DEFAULT_GW:	
			break;
		case CWMP_WAN_IP_CONN_DNS_ENABLED:	
			break;
		case CWMP_WAN_IP_CONN_DNS_OVERRIDE_ALLOWED:	
			break;
		case CWMP_WAN_IP_CONN_DNS_SERVERS:					
			break;
		case CWMP_WAN_IP_CONN_MAX_MTUSIZE:
			break;
		case CWMP_WAN_IP_CONN_MACADDR:
			break;
		case CWMP_WAN_IP_CONN_MACADDR_OVERRIDE:
			break;
		case CWMP_WAN_IP_CONN_ROUTER_PROTOCOL_RX:
			break;
		case CWMP_WAN_IP_CONN_SHAPING_RATE:
			break;
		case CWMP_WAN_IP_CONN_SHAPING_BURST_SIZE:
			break;
		case CWMP_WAN_IP_CONN_RESET:
			break;
		case CWMP_WAN_IP_CONN_ENABLE:	
			break;
		case CWMP_WAN_IP_CONN_POSSIBLE_CONN_TYPE:
			break;
		case CWMP_WAN_IP_CONN_UPTIME:	
			break;
		case CWMP_WAN_IP_CONN_LAST_CONN_ERROR:		
			break;
		case CWMP_WAN_IP_CONN_RSIP_AVAILABLE:								
			break;
		case CWMP_WAN_IP_CONN_PORTMAPPING_NUM_ENTRIES:	
			break;
		case CWMP_VLAN_ENABLE:
			break;
		case CWMP_VLAN_NAME:
			break;
		case CWMP_VLAN_ID:
			break;
		case CWMP_WAN_ETHERNET_LINK_STATUS:
			break;
		case CWMP_ASSOC_DEVICE_MACADDR:														
			break;
		case CWMP_ASSOC_DEVICE_IPADDR:		
			break;
		case CWMP_ASSOC_DEVICE_AUTHSTATE:		
			break;
		case CWMP_ASSOC_DEVICE_LAST_REQ_UNICAST_CIPHER:
			break;
		case CWMP_ASSOC_DEVICE_LAST_REQ_MULTICAST_CIPHER:
			break;
		case CWMP_ASSOC_DEVICE_LAST_PMKLD:		
			break;
		case CWMP_ASSOC_DEVICE_LAST_DATA_TRANSMIT_RATE:	
			break;
		case CWMP_CONNECTION_ACTIVE_CONN_DEVICE_CONTAINER:			
			break;
		case CWMP_CONNECTION_ACTIVE_CONN_SERVICEID:
			break;
		case CWMP_HOST_IPADDR:
			break;
		case CWMP_HOST_ADDR_SOURCE:
			break;
		case CWMP_HOST_LEASE_TIME_REMAINING:
			break;
		case CWMP_HOST_MACADDR:
			break;
		case CWMP_HOST_NAME:
			break;
		case CWMP_HOST_INTERFACETYPE:
			break;
		case CWMP_HOST_ACTIVE:
			break;
		case CWMP_HOST_LAYER2INTERFACE:
			break;
		case CWMP_HOST_VENDORCLASSID:
			break;
		case CWMP_HOST_CLIENTID:
			break;
		case CWMP_HOST_USERCLASSID:
			break;
		case CWMP_WPS_ENABLE:
			break;
		case CWMP_WPS_DEVICENAME:		
			break;
		case CWMP_WPS_DEVICEPW:	
			break;
		case CWMP_STATS_BYTES_SENT:	
			break;
		case CWMP_STATS_BYTES_RECEIVED:	
			break;
		case CWMP_STATS_PACKETS_SENT:	
			break;
		case CWMP_STATS_PACKETS_RECEIVED:
			break;
		case CWMP_STATS_ERRORS_SENT:
			break;
		case CWMP_STATS_ERRORS_RECEIVED:
			break;
		case CWMP_STATS_UNICAST_PACKETS_SENT:		
			break;
		case CWMP_STATS_UNICAST_PACKETS_RECEIVED:		
			break;
		case CWMP_STATS_DISCARD_PACKETS_SENT:			
			break;
		case CWMP_STATS_DISCARD_PACKETS_RECEIVED:	
			break;
		case CWMP_STATS_MULTICAST_PACKETS_SENT:
			break;
		case CWMP_STATS_MULTICAST_PACKETS_RECEIVED:
			break;
		case CWMP_STATS_BROADCAST_PACKETS_SENT:	
			break;
		case CWMP_STATS_BROADCAST_PACKETS_RECEIVED:	
			break;
		case CWMP_STATS_UNKNOWN_PROTO_PACKETS_RECEIVED:
			break;
		case CWMP_IP_INTERFACE_ENABLE:	
			break;
		case CWMP_IP_INTERFACE_IPADDR:						
			break;
		case CWMP_IP_INTERFACE_SUBNETMASK:			
			break;
		case CWMP_IP_INTERFACE_ADDRTYPE:					
			break;
		case CWMP_WLAN_SSID_TX_OVER_ENABLE:
			break;
		case CWMP_WLAN_SSID_RX_OVER_ENABLE:
			break;
		case CWMP_WLAN_SSID_CONN_OVER_ENABLE:
			break;
		case CWMP_WAN_IP_CONN_NUM_ENTRIES:
			break;
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_ENABLE:
			break;
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_STATUS:
			break;						
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_MAC:		
			break;						
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_MAXBITRATE:	
			break;						
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE:		
			break;					
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPINGRATE:			
			break;				
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPING_BURSTSIZE:	
			break;			
		case CWMP_ENABLED_INTERNET:
			break;
		case CWMP_WAN_ACCESSTYPE: 
			break;
		case CWMP_LAYER1_UPSTREAM_MAXBITRATE: 
			break;
		case CWMP_LAYER1_DOWNSTREAM_MAXBITRATE:
			break;
		case CWMP_PHYSICAL_LINK_STATUS:
			break;
		case CWMP_WAN_ACCESS_PROVIDER:
			break;
		case CWMP_WAN_TOTAL_BYTES_SENT:
			break;
		case CWMP_WAN_TOTAL_BYTES_RECEIVED:
			break;
		case CWMP_WAN_TOTAL_PACKETS_SENT:
			break;
		case CWMP_WAN_TOTAL_PACKETS_RECEIVED:
			break;
		case CWMP_WAN_MAX_ACTIVE_CONN:
			break;
		case CWMP_WAN_NUM_ACTIVE_CONN:
			break;
		case CWMP_HOST_NUM_ENTRIES:		
			break;
		case CWMP_WLAN_CONF_ENABLE:
			break;
		case CWMP_WLAN_CONF_STATUS:			
			break;
		case CWMP_WLAN_CONF_BSSID:			
			break;
		case CWMP_WLAN_CONF_MAXBITRATE:	
			break;
		case CWMP_WLAN_CONF_CHANNEL:				
			break;
		case CWMP_WLAN_CONF_SSID:					
			break;
		case CWMP_WLAN_CONF_BEACONTYPE: 			
			break;
		case CWMP_WLAN_CONF_MAC_CONTROL_ENABLE:		
			break;
		case CWMP_WLAN_CONF_STANDARD: 							
			break;
		case CWMP_WLAN_CONF_WEP_KEYINDEX:					
			break;
		case CWMP_WLAN_CONF_KEY_PASSPHRASE:	
			break;
		case CWMP_WLAN_CONF_WEP_ENCRYPT_LEVEL:		
			break;
		case CWMP_WLAN_CONF_BASIC_ENCRYPT_MODES:		
			break;
		case CWMP_WLAN_CONF_BASIC_AUTH_MODE: 				
			break;
		case CWMP_WLAN_CONF_WPA_ENCRYPT_MODES: 			
			break;
		case CWMP_WLAN_CONF_WPA_AUTH_MODE: 					
			break;
		case CWMP_WLAN_CONF_IEEE11I_ENCTYPT_MODES:			
			break;
		case CWMP_WLAN_CONF_IEEE11I_AUTH_MODES: 					
			break;
		case CWMP_WLAN_CONF_POSSIBLE_CHANNELS: 				
			break;
		case CWMP_WLAN_CONF_BASIC_DATA_TRANSMIT_RATES: 		
			break;
		case CWMP_WLAN_CONF_OPERATION_DATA_TRANSMIT_RATES: 		
			break;
		case CWMP_WLAN_CONF_POSSIBLE_DATA_TRANSMIT_RATES:	
			break;
		case CWMP_WLAN_CONF_INSECURE_OOB_ACCESS_ENABLED:		
			break;
		case CWMP_WLAN_CONF_BEACON_ADVERTISE_ENABLED: 		
			break;
		case CWMP_WLAN_CONF_RADIO_ENABLED: 					
			break;
		case CWMP_WLAN_CONF_ARF_ENABLED: 							
			break;
		case CWMP_WLAN_CONF_LOCATION_DESCRIPTION: 			
			break;
		case CWMP_WLAN_CONF_REGULATORY_DOMAIN: 				
			break;
		case CWMP_WLAN_CONF_TOTAL_PSK_FAILURES: 			
			break;
		case CWMP_WLAN_CONF_TOTAL_INTEGRITY_FAILURES: 	
			break;
		case CWMP_WLAN_CONF_CHANNEL_IN_USE:
			break;
		case CWMP_WLAN_CONF_DEVICE_OPERATION_MODE: 		
			break;
		case CWMP_WLAN_CONF_DISTANCE_FROM_ROOT: 				
			break;
		case CWMP_WLAN_CONF_PEER_BSSID: 							
			break;
		case CWMP_WLAN_CONF_AUTH_SERVICE_MODE: 				
			break;
		case CWMP_WLAN_CONF_TOTAL_BYTES_SENT: 				
			break;
		case CWMP_WLAN_CONF_TOTAL_BYTES_RECEIVED: 			
			break;
		case CWMP_WLAN_CONF_TOTAL_PACKETS_SENT:				
			break;
		case CWMP_WLAN_CONF_TOTAL_PACKETS_RECEIVED: 			
			break;
		case CWMP_WLAN_CONF_TOTAL_ASSOCIATIONS: 					
			break;
		case CWMP_WLAN_CONF_NAME: 												
			break;
		case CWMP_WLAN_CONF_AUTO_CHANNEL_ENABLE: 				
			break;
		case CWMP_WLAN_CONF_SSID_ADVERTISE_ENABLED: 			
			break;
		case CWMP_WLAN_CONF_TRANSMIT_POWER_SUPPORTED: 		
			break;
		case CWMP_WLAN_CONF_TRANSMIT_POWER: 				
			break;
		case CWMP_WLAN_CONF_WMM_SUPPORTED: 			
			break;
		case CWMP_WLAN_CONF_UAPSD_SUPPORTED: 		
			break;
		case CWMP_WLAN_CONF_WMM_ENABLE: 				
			break;
		case CWMP_WLAN_CONF_UAPSD_ENABLE: 				
			break;
		case CWMP_AP_WMM_PARAMETER_NUM_ENTRIES: 	
			break;
		case CWMP_STA_WMM_PARAMETER_NUM_ENTRIES:	
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_ENABLE:	
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_STATUS: 		
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC:	
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC_CONTROL_ENABLE:
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAXBITRATE: 														
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE: 														
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_NAME: 			
			break;
		case CWMP_DHCPSERVERCONF:
			break;	
		case CWMP_DHCPSERVERENABLE:					
			break;	
		case CWMP_DHCPLEASETIME:
			nvram_safe_get_r("lan_lease", ptr, ptr_size-1);
			break;	
		case CWMP_FORWARDING_ENABLE: 
			break;
		case CWMP_FORWARDING_STATUS: 	
			break;
		case CWMP_FORWARDING_TYPE:		
			break;
		case CWMP_FORWARDING_DEST_IPADDR: 		
			break;
		case CWMP_FORWARDING_DEST_SUBNETMASK:
			break;
		case CWMP_FORWARDING_SRC_IPADDR:
			break;
		case CWMP_FORWARDING_SRC_SUBNETMASK:
			break;
		case CWMP_FORWARDING_GATEWAY_IPADDR:	
			break;
		case CWMP_FORWARDING_INTERFACE:
			break;
		case CWMP_FORWARDING_METRIC:
			break;
		case CWMP_FORWARDING_MTU:	
			break;
		case CWMP_FORWARDING_POLICY:
			break;
		case CWMP_FORWARDING_STATIC_ROUTE:
			break;
		case CWMP_ATCLIST_IPADDR:
			break;
		case CWMP_WS_IPADDR:
			break;
		case CWMP_WS_PORT:
			break;
		case CWMP_WEBMNGMT_SERVER_ENABLE:	
			break;
		case CWMP_WEBMNGMT_SERVER_LOGIN_IPADDR:
			break;
		case CWMP_WEBMNGMT_SERVER_LOGIN_PORT: 
			break;
		case CWMP_WEBMNGMT_SERVER_LOGINKEY:
			break;
		case CWMP_QMS_IPADDRESS:
			break;
		case CWMP_QMS_PORT1: 	
			break;
		case CWMP_QMS_PORT2:
			break;
		case CWMP_TELNET_ACCESSLIST_IPADDRESS:
			break;
		case CWMP_TELNET_ACCESSLIST_PORT:
			break;
		case CWMP_RADIUS_AUTH_PORT:
			break;
		case CWMP_RADIUS_AUTH_IPADDRESS:
			break;
		case CWMP_WAN_CONN_NUM_ENTRIES:
			break;
		case CWMP_LAN_USB_INTERFACE_NUM_ENTRIES:
			break;
		case CWMP_RADIUS_ACC_PORT:
			break;
		case CWMP_RADIUS_ACC_IPADDRESS:
			break;
		case CWMP_MANUFACTURER:
			break;
		case CWMP_MANUFACTURER_OUI:
			break;
		case CWMP_MODELNAME:
			break;
		case CWMP_DESCRIPTION:
			break;
		case CWMP_PRODUCTCLASS:
			break;
		case CWMP_SERIAL_NUM:
			break;
		case CWMP_HW_VER:
			break;
		case CWMP_SW_VER:
			break;
		case CWMP_MODEM_FIRMWARE_VER:
			break;
		case CWMP_ENABLED_OPTIONS:
			break;
		case CWMP_ADDITIONAL_HW_VER:
			break;
		case CWMP_ADDITIONAL_SW_VER:
			break;
		case CWMP_SPEC_VER:
			break;
		case CWMP_PROVISIONINGCODE:
			break;
		case CWMP_FIRSTUSEDATE:
			break;
		case CWMP_DEVICELOG:
			break;
		case CWMP_VENDOR_CONFIGFILE_NUM_ENTRIES:
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_NUM_ENTRIES:
			break;
		case CWMP_LAN_WLAN_CONF_NUM_ENTRIES:
			break;
		case CWMP_DEFAULT_CONN_SERVICE:
			break;
		case CWMP_FORWARD_NUM_ENTRIES:
			break;
		case CWMP_NTPSERVER1:
			break;			
		case CWMP_NTPSERVER2:
			break;	
		case CWMP_NTPSERVER3:
			break;	
		case CWMP_NTPSERVER4:
			break;	
		case CWMP_NTPSERVER5:
			break;
		case CWMP_CURRENT_LOCALTIME:
			break;
		case CWMP_LOCALTIMEZONE:
			break;
		case CWMP_LOCALTIMEZONENAME:
			break;
		case CWMP_DAYLIGHT_SAVING_USED: 				
			break;
		case CWMP_DAYLIGHT_SAVING_START: 	
			break;
		case CWMP_DAYLIGHT_SAVING_END:	
			break;
		case CWMP_TIME_ENABLE:
			break;
		case CWMP_TIME_STATUS:
			break;
		case CWMP_VENDOR_CONFIGFILE_NAME:
			break;
		case CWMP_VENDOR_CONFIGFILE_VER:	 	
			break;
		case CWMP_VENDOR_CONFIGFILE_DATE: 	
			break;
		case CWMP_VENDOR_CONFIGFILE_DESCRIPTION:
			break;
		case CWMP_FIRMWARE_VER:
			break;
		case CWMP_FIRMWARE_PREVER:
			break;
		case CWMP_FIRMWARE_URL: 
			break;
		case CWMP_FIRMWARE_USERNAME:
			break;
		case CWMP_FIRMWARE_PW:		
			break;
		case CWMP_FIRMWARE_PACKAGE_SIZE: 				
			break;
		case CWMP_FIRMWARE_PACKAGE_VER: 		
			break;
		case CWMP_FIRMWARE_PACKAGE_FILENAME: 	
			break;
		case CWMP_FIRMWARE_RESULTCODE: 	
			break;
		case CWMP_FIRMWARE_RESULT_ERRMSG: 	
			break;
		case CWMP_FIRMWARE_LAST_PACKAGE_DOWNLOAD_DATE:
			break;
		case CWMP_FIRMWARE_LAST_UPGRADE_DATE:			
			break;
		case CWMP_FIRMWARE_CONTROL_TRAFFIC:	
			break;
		case CWMP_FIRMWARE_DOWNLOAD_RETRIES:
			break;
		case CWMP_FIRMWARE_DOWNLOAD_TIMEOUT:	
			break;
		case CWMP_MONTIME:
		{
			char *mon_time = nvram_safe_get_r("dv_mon_time", ptr, ptr_size);
			if (*mon_time == 0)
				snprintf((char*)ptr, ptr_size, "%s", "00:00");
		}
			break;
		case CWMP_MONRANGE:
		{
			int range = atoi(nvram_safe_get_r("dv_mon_range", buf, sizeof(buf)));
			snprintf((char*)ptr, ptr_size, "%d", range);
		}
			break;
		case CWMP_MONDAYS:
		{
			int period = atoi(nvram_safe_get_r("dv_mon_days", buf, sizeof(buf)));
			snprintf((char*)ptr, ptr_size, "%d", period);
		}
			break;
		case CWMP_MONPERIOD:
			{
				char buf[32];
				int period = atoi(nvram_safe_get_r("dv_mon_period", buf, sizeof(buf)));
				snprintf((char*)ptr, ptr_size, "%d", period);
			}
			break;
		case CWMP_BASIC_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_basic_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s","0");
			}
			break;
		case CWMP_CONFIG_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_config_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_WLAN_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_wifi_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_QOS_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_qos_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_SERVER_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_server_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_MON_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_mon_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_ACL_INFO_ENABLE:
			{
				char buf[4];
				char *p = nvram_get_r("dv_mon_acl_info", buf, sizeof(buf));
				if (p != NULL)
					snprintf((char*)ptr, ptr_size, "%s", p);
				else
					snprintf((char*)ptr, ptr_size, "%s", "0");
			}
			break;
		case CWMP_WLAN_NUM_ENTRIES:
			break;
		case CWMP_HOST:
			break;
		case CWMP_FLAG:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] TODO...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api));
			break;
		case CWMP_CERT_PASSWORD:
			nvram_safe_get_r("cwmp_cert_password", ptr, ptr_size);
			break;
		case CWMP_RB_COMMANDKEY: 		/* string */
			nvram_safe_get_r("cwmp_rb_comanndkey", ptr, ptr_size);
			break;
		case CWMP_DL_COMMANDKEY: 		/* string */
			snprintf((char*)ptr, ptr_size, "%s", (char*)nvram_safe_get("cwmp_dl_commandkey"));
			break;
		case CWMP_DL_STARTTIME: 		/* intiger */
			{
				char tmp[128];

				snprintf((char*)tmp, sizeof(tmp), "%s", (char*)nvram_safe_get("cwmp_dl_starttime"));
				bcmcfg_debug_printf(stderr, "[%s():%d] s1, event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);

				if( !STRLEN(tmp)) {
					return 0;
				}

				*(unsigned int*)ptr = (unsigned int)atoi(tmp);

				bcmcfg_debug_printf(stderr, "[%s():%d] s2, event=[%s] value=[%d]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (unsigned int)atoi(tmp));
			}
			return 1;
			break;
		case CWMP_DL_COMPLETETIME: 		/* intiger */
			{
				char tmp[128];

				snprintf((char*)tmp, sizeof(tmp), "%s", (char*)nvram_safe_get("cwmp_dl_completetime"));
				bcmcfg_debug_printf(stderr, "[%s():%d] s1, event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);

				if( !STRLEN(tmp)) {
					return 0;
				}

				*(unsigned int*)ptr = (unsigned int)atoi(tmp);

				bcmcfg_debug_printf(stderr, "[%s():%d] s2, event=[%s] value=[%d]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (unsigned int)atoi(tmp));
			}
			return 1;
			break;
		case CWMP_DL_FAULTCODE: 		/* intiger */
			{
				char tmp[128];

				nvram_safe_get_r("cwmp_dl_faultcode", tmp, sizeof(tmp));
				bcmcfg_debug_printf(stderr, "[%s():%d] s1, event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);

				if( !STRLEN(tmp)) {
					return 0;
				}

				*(unsigned int*)ptr = (unsigned int)atoi(tmp);

				bcmcfg_debug_printf(stderr, "[%s():%d] s2, event=[%s] value=[%d]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (unsigned int)atoi(tmp));
			}
			return 1;
			break;
		case CWMP_INFORM_EVENTCODE: 	/* integer */
			{
				char tmp[128];

				nvram_safe_get_r("cwmp_inform_eventcode", tmp, sizeof(tmp));
				nvram_unset("cwmp_inform_eventcode");
				bcmcfg_debug_printf(stderr, "[%s():%d] s1, event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);

				if( !STRLEN(tmp)) {
					return 0;
				}

				*(unsigned int*)ptr = (unsigned int)atoi(tmp);

				bcmcfg_debug_printf(stderr, "[%s():%d] s2, event=[%s] value=[%d]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (unsigned int)atoi(tmp));
			}
			return 1;
			break;
		case CWMP_TRCS_URL: 				/* string */
		{
			char server[64], url[64], *val, *ptr2;
			char method[8];
			memset(server, 0, sizeof(server));
			memset(url, 0, sizeof(url));
			memset(method, 0, sizeof(method));
			//val= nvram_safe_get_r("cwmp_rcs_url", buf, sizeof(buf));
			val= nvram_safe_get_r("cwmp_trcs_url", buf, sizeof(buf));
			if (!val || STRLEN(val) < 1)
				break;

			ptr2 = strstr(val, "://");
			if (ptr2 && STRLEN(ptr2) > 3) {
				*ptr2=0;
				strncpy(method, val, sizeof(method)-1);
				val = ptr2+3;
			}
			if (method[0] ==0)
				snprintf(method, sizeof(method), "%s", "https");
			ptr2 = strchr(val, '/');
			if (ptr2 && STRLEN(ptr2)>1) {
				*ptr2 = 0;
				snprintf(server, sizeof(server), "%s", val);
				snprintf(url, sizeof(url), "%s", ptr2+1);
			} else
				snprintf(server, sizeof(server), "%s", val);
			if (STRLEN(url) > 0) {
				if (strstr(url, "cwmp_d"))
					snprintf((char *)ptr, ptr_size, "%s://%s/%s", method, server, url);
				else
					snprintf((char *)ptr, ptr_size, "%s://%s/%s/cwmp_d",method, server, url);
			} else {
				snprintf((char *)ptr, ptr_size, "%s://%s/cwmp_d", method, server);
			}
		}
			break;
		case CWMP_ACS_URL: 				/* string */
		{
			char server[64], url[64], *val, *ptr2;
			char method[8];
			memset(server, 0, sizeof(server));
			memset(url, 0, sizeof(url));
			memset(method, 0, sizeof(method));
			val= nvram_safe_get_r("cwmp_acs_url", buf, sizeof(buf));
			if (!val || STRLEN(val) < 1)
				break;

			ptr2 = strstr(val, "://");
			if (ptr2 && STRLEN(ptr2) > 3) {
				*ptr2=0;
				strncpy(method, val, sizeof(method)-1);
				val = ptr2+3;
			}
			if (method[0] ==0)
				snprintf(method, sizeof(method), "%s", "https");
			ptr2 = strchr(val, '/');
			if (ptr2 && STRLEN(ptr2)>1) {
				*ptr2 = 0;
				snprintf(server, sizeof(server), "%s", val);
				snprintf(url, sizeof(url), "%s", ptr2+1);
			} else
				snprintf(server, sizeof(server), "%s", val);
			if (STRLEN(url) > 0) {
				if (strstr(url, "cwmp_d"))
					snprintf((char *)ptr, ptr_size, "%s://%s/%s", method, server, url);
				else
					snprintf((char *)ptr, ptr_size, "%s://%s/%s/cwmp_d",method, server, url);
			} else {
				snprintf((char *)ptr, ptr_size, "%s://%s/cwmp_d", method, server);
			}
		}
			break;
		case CWMP_ACS_USERNAME: 		/* string */
		{
			int i, j;
			char *rslt_ptr = (char *)ptr;
			char model_name[16] = "";

			get_wan_macaddr(tmp, sizeof(tmp), LOWER);
			str_lower(tmp);
			get_model(model_name, sizeof(model_name), LOWER);            
			snprintf(buf, sizeof(buf), "%s^%s", model_name, tmp);
			strncpy(rslt_ptr, buf, STRLEN(buf));

#if 1
			for (i=0, j=0; STRLEN(buf) && j < ptr_size; i++) {
#if 0
			for (i=0, j=0; STRLEN(buf) && j < ptr_size; i++) {
				if (buf[i] == ':')
					j+= snprintf((char *)(ptr+j), ptr_size-j, "%s", "\%3A");
				else
					j+= snprintf((char *)(ptr+j), ptr_size-j, "%c", buf[i]);
#endif
				//url encode acs username
#if 1
				if (buf[i] == ':') {
					strncpy(rslt_ptr + j, "\%3A", 3);
					j += 3;
				} else {
					rslt_ptr[j++] = buf[i];
				}
#else

#endif
			}
#endif
		
		}
			break;
		case CWMP_ACS_PASSWORD: 		/* string */
//			snprintf((char*)ptr, ptr_size, "%s", (char*)nvram_safe_get("cwmp_acs_password"));
#ifndef __LGU_PUF__
			nvram_safe_get_r("cwmp_acs_password", ptr, ptr_size-1);	
#else	
			{	
				int ret;
				ret = secc_get_data(0, "cwmp_acs_password", (char *)ptr, ptr_size);
				if (ret == 0) {
					fprintf(stdout, "get value [%s]\n", (char *)ptr); //success
				} else {
					fprintf(stdout, "get ret %d (0x%x)\n", ret, ret); //""
					memset(ptr, 0, ptr_size);
				}
			}
#endif
			return 1;
		case CWMP_CPE_SERVER_PORT: 		/* intiger */
			{
				char tmp[128];

				snprintf((char*)tmp, sizeof(tmp), "%s", (char*)nvram_safe_get("cwmp_cpe_server_port"));
				bcmcfg_debug_printf(stderr, "[%s():%d] s1, event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);

				if( !STRLEN(tmp)) {
					return 0;
				}

				*(unsigned int*)ptr = (unsigned int)atoi(tmp);
			}
			return 1;
			break;
		case CWMP_CONREQ_USERNAME: 		/* string */
			get_wan_macaddr(tmp, sizeof(tmp), LOWER);
			str_lower(tmp);
			snprintf(ptr, ptr_size, "%s^%s", DV_PRODUCT_NAME_LOWERCASE, tmp);
			break;
		case CWMP_CONREQ_PASSWORD: 		/* string */
#ifndef __LGU_PUF__
			nvram_safe_get_r("cwmp_acs_password", ptr, ptr_size-1);	
#else	
			{	
				int ret;
				ret = secc_get_data(0, "cwmp_acs_password", (char *)ptr, ptr_size);
				if (ret == 0) {
					fprintf(stdout, "get value [%s]\n", (char *)ptr); //success
				} else {
					fprintf(stdout, "get ret %d (0x%x)\n", ret, ret); //""
					memset(ptr, 0, ptr_size);
				}
			}
#endif
			break;
		case CWMP_INFORM_ENABLE: 		/* intiger */
			nvram_safe_get_r("cwmp_periodic_inform", tmp, sizeof(tmp));
			if (tmp[0]==0)
				snprintf(tmp, sizeof(tmp), "%s", "1");
			*(unsigned int*)ptr = strtoul(tmp, NULL, 10);
			return 1;
			break;
		case CWMP_INFORM_INTERVAL: 		/* intiger */
			nvram_safe_get_r("cwmp_periodic_interval", tmp, sizeof(tmp));
			*(unsigned int*)ptr = strtoul(tmp, NULL, 10);
			return 1;
			break;
		case CWMP_INFORM_TIME: 			/* intiger */
			nvram_safe_get_r("cwmp_periodic_time", tmp, sizeof(tmp));
			*(unsigned int*)ptr = strtoul(tmp, NULL, 10);
			return 1;
			break;
		case CWMP_ACS_UPGRADESMANAGED: 	/* string */
			snprintf((char*)ptr, ptr_size, "%s", (char*)nvram_safe_get("cwmp_acs_upgradesmanaged"));
			break;
		default:
			bcmcfg_debug_printf(stderr, "[%s():%d] Unkown Event...\n", __FUNCTION__, __LINE__);
			break;
	}

	bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);

	if( !STRLEN(ptr)) {
		return 0;
	}

	return 1;
}

int bcm_cfg_set( int api, void *ptr, int ptr_size)
{
	switch(api) {
		case CWMP_PORT_MAPPING_POLICY_PROTOCOL:
			break;
		case CWMP_PORT_MAPPING_POLICY_EXTERNAL_PORT:		
			break;
		case CWMP_PORT_MAPPING_POLICY_INTERNAL_PORT:	
			break;
		case CWMP_PORT_MAPPING_ENABLED:						
			break;
		case CWMP_PORT_MAPPING_LEASE_DURATION:
			break;
		case CWMP_PORT_MAPPING_REMOTE_HOST:
			break;
		case CWMP_PORT_MAPPING_EXTERNAL_PORT:
			break;
		case CWMP_PORT_MAPPING_INTERNAL_PORT:
			break;
		case CWMP_PORT_MAPPING_PROTOCOL:
			break;
		case CWMP_PORT_MAPPING_INTERNAL_CLIENT:
			break;
		case CWMP_PORT_MAPPING_DESCRIPTION:
			break;
		case CWMP_PORT_MAPPING_EXTERNAL_PORT_END_RANGE:
			break;
		case CWMP_WAN_IP_ENABLE:
			break;
		case CWMP_WAN_IP_CONN_TYPE:
			break;
		case CWMP_WAN_IP_CONN_NAME:	
			break;
		case CWMP_WAN_IP_CONN_AUTO_DISCONN_TIME:	
			break;
		case CWMP_WAN_IP_CONN_IDLE_DISCONN_TIME:		
			break;
		case CWMP_WAN_IP_CONN_WARN_DISCONN_DELAY:	
			break;
		case CWMP_WAN_IP_CONN_NAT_ENABLED:	
			break;
		case CWMP_WAN_IP_CONN_ADDRESSING_TYPE:	
			set_wan_proto((char *)ptr);
			break;
		case CWMP_WAN_IP_CONN_EXTERNAL_IPADDR:
			break;
		case CWMP_WAN_IP_CONN_SUBNETMASK:
			break;
		case CWMP_WAN_IP_CONN_DEFAULT_GW:	
			break;
		case CWMP_WAN_IP_CONN_DNS_ENABLED:	
			break;
		case CWMP_WAN_IP_CONN_DNS_OVERRIDE_ALLOWED:	
			break;
		case CWMP_WAN_IP_CONN_DNS_SERVERS:					
			break;
		case CWMP_WAN_IP_CONN_MAX_MTUSIZE:
			break;
		case CWMP_WAN_IP_CONN_MACADDR:
			break;
		case CWMP_WAN_IP_CONN_MACADDR_OVERRIDE:
			break;
		case CWMP_WAN_IP_CONN_ROUTER_PROTOCOL_RX:
			break;
		case CWMP_WAN_IP_CONN_SHAPING_RATE:
			break;
		case CWMP_WAN_IP_CONN_SHAPING_BURST_SIZE:
			break;
		case CWMP_WAN_IP_CONN_RESET:
			break;
		case CWMP_VLAN_ENABLE:
			break;
		case CWMP_VLAN_NAME:
			break;
		case CWMP_VLAN_ID:
			break;
		case CWMP_WPS_ENABLE:
			break;
		case CWMP_WPS_DEVICEPW:	
			break;
		case CWMP_IP_INTERFACE_ENABLE:	
			break;
		case CWMP_IP_INTERFACE_IPADDR:						
			break;
		case CWMP_IP_INTERFACE_SUBNETMASK:			
			break;
		case CWMP_IP_INTERFACE_ADDRTYPE:					
			break;
		case CWMP_WLAN_SSID_TX_OVER_ENABLE:
			break;
		case CWMP_WLAN_SSID_RX_OVER_ENABLE:
			break;
		case CWMP_WLAN_SSID_CONN_OVER_ENABLE:
			break;
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_ENABLE:
			break;
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_MAXBITRATE:	
			break;						
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE:		
			break;					
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPINGRATE:			
			break;				
		case CWMP_WAN_ETHERNET_INTERFACE_CONF_SHAPING_BURSTSIZE:	
			break;			
		case CWMP_ENABLED_INTERNET:
			break;
		case CWMP_WLAN_CONF_ENABLE:
			break;
		case CWMP_WLAN_CONF_MAXBITRATE: 
			break;
		case CWMP_WLAN_CONF_CHANNEL:
			break;
		case CWMP_WLAN_CONF_SSID:
			break;
		case CWMP_WLAN_CONF_BEACONTYPE:
			break;
		case CWMP_WLAN_CONF_MAC_CONTROL_ENABLE:
			break;
		case CWMP_WLAN_CONF_WEP_KEYINDEX:
			break;
		case CWMP_WLAN_CONF_KEY_PASSPHRASE:
			break;
		case CWMP_WLAN_CONF_BASIC_ENCRYPT_MODES:
			break;
		case CWMP_WLAN_CONF_BASIC_AUTH_MODE:
			break;
		case CWMP_WLAN_CONF_WPA_ENCRYPT_MODES:
			break;
		case CWMP_WLAN_CONF_WPA_AUTH_MODE:
			break;
		case CWMP_WLAN_CONF_IEEE11I_ENCTYPT_MODES:
			break;
		case CWMP_WLAN_CONF_IEEE11I_AUTH_MODES:
			break;
		case CWMP_WLAN_CONF_BASIC_DATA_TRANSMIT_RATES:
			break;
		case CWMP_WLAN_CONF_OPERATION_DATA_TRANSMIT_RATES:
			break;
		case CWMP_WLAN_CONF_INSECURE_OOB_ACCESS_ENABLED:
			break;
		case CWMP_WLAN_CONF_BEACON_ADVERTISE_ENABLED:
			break;
		case CWMP_WLAN_CONF_RADIO_ENABLED:
			break;
		case CWMP_WLAN_CONF_ARF_ENABLED:
			break;
		case CWMP_WLAN_CONF_LOCATION_DESCRIPTION:
			break;
		case CWMP_WLAN_CONF_REGULATORY_DOMAIN:
			break;
		case CWMP_WLAN_CONF_DEVICE_OPERATION_MODE:
			break;
		case CWMP_WLAN_CONF_DISTANCE_FROM_ROOT:
			break;
		case CWMP_WLAN_CONF_PEER_BSSID:
			break;
		case CWMP_WLAN_CONF_AUTH_SERVICE_MODE:
			break;
		case CWMP_WLAN_CONF_AUTO_CHANNEL_ENABLE:
			break;
		case CWMP_WLAN_CONF_SSID_ADVERTISE_ENABLED:
			break;
		case CWMP_WLAN_CONF_TRANSMIT_POWER:
			break;
		case CWMP_WLAN_CONF_WMM_ENABLE:
			break;
		case CWMP_WLAN_CONF_UAPSD_ENABLE:
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_ENABLE:	
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAC_CONTROL_ENABLE:
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_MAXBITRATE: 														
			break;
		case CWMP_LAN_ETHERNET_INTERFACE_CONF_DUPLEXMODE: 														
			break;
		case CWMP_DHCPSERVERCONF:
			break;	
		case CWMP_DHCPSERVERENABLE:					
			break;	
		case CWMP_DHCPLEASETIME:
			nvram_set("lan_lease", ptr);
			break;	
		case CWMP_WS_IPADDR:
			break;
		case CWMP_WS_PORT:
			break;
		case CWMP_WEBMNGMT_SERVER_ENABLE:	
			break;
		case CWMP_WEBMNGMT_SERVER_LOGIN_IPADDR:
			break;
		case CWMP_WEBMNGMT_SERVER_LOGIN_PORT: 
			break;
		case CWMP_WEBMNGMT_SERVER_LOGINKEY:
			break;
		case CWMP_TELNET_ACCESSLIST_IPADDRESS:
			break;
		case CWMP_TELNET_ACCESSLIST_PORT:
			break;
		case CWMP_PROVISIONINGCODE: 	/* string */
			break;
		case CWMP_DEFAULT_CONN_SERVICE:
			break;
		case CWMP_NTPSERVER1:
			break;			
		case CWMP_NTPSERVER2:
			break;	
		case CWMP_NTPSERVER3:
			break;	
		case CWMP_NTPSERVER4:
			break;	
		case CWMP_NTPSERVER5:
			break;
		case CWMP_LOCALTIMEZONE:
			break;
		case CWMP_LOCALTIMEZONENAME:
			break;
		case CWMP_DAYLIGHT_SAVING_USED: 				
			break;
		case CWMP_DAYLIGHT_SAVING_START: 	
			break;
		case CWMP_DAYLIGHT_SAVING_END:	
			break;
		case CWMP_TIME_ENABLE:
			break;
		case CWMP_MONTIME:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_MONRANGE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_MONDAYS:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_MONPERIOD:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_BASIC_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_CONFIG_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_WLAN_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_QOS_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_SERVER_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_MON_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_ACL_INFO_ENABLE:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_FLAG:
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] TODO...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api));
			break;
		case CWMP_CERT_PASSWORD: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_cert_password", "");
			} else {
				nvram_set("cwmp_cert_password", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_RB_COMMANDKEY: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_rb_commandkey", "");
			} else {
				nvram_set("cwmp_rb_commandkey", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_DL_COMMANDKEY: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_dl_commandkey", "");
			} else {
				nvram_set("cwmp_dl_commandkey", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_DL_STARTTIME: 		/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("acs_con_starttime", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("acs_con _starttime", (char*)tmp); 
				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_DL_COMPLETETIME: 		/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_dl_completetime", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_dl_completetime", (char*)tmp); 
				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_DL_FAULTCODE: 		/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_dl_faultcode", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_dl_faultcode", (char*)tmp); 
				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_INFORM_EVENTCODE: 	/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_inform_eventcode", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_inform_eventcode", (char*)tmp); 

				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_ACS_URL: 				/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_acs_url", "");
			} else {
				nvram_set("cwmp_acs_url", ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_ACS_PASSWORD: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_acs_password", "");
			} else {
#ifndef __LGU_PUF__
				nvram_set("cwmp_acs_password", (char*)ptr); 
#else		
				int ret;
				ret = secc_set_data(0, "cwmp_acs_password", ptr);	//pid, nvram index, value
				fprintf(stdout, "set ret %d (0x%x)\n", ret, ret);
				nvram_set("cwmp_acs_password", (char*)ptr); 
#endif
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_CPE_SERVER_PORT: 		/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_cpe_server_port", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_cpe_server_port", (char*)tmp); 

				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_CONREQ_USERNAME: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_conreq_username", "");
			} else {
				nvram_set("cwmp_conreq_username", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_CONREQ_PASSWORD: 		/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_conreq_password", "");
			} else {
				nvram_set("cwmp_conreq_password", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		case CWMP_INFORM_ENABLE: 		/* intiger */
		{
			char tmp[128] = "";

			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_periodic_inform", "");
				tmp[0]=0;
			} else {
				snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
				nvram_set("cwmp_periodic_inform", (char*)tmp); 
			}

			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
		}
			break;
		case CWMP_INFORM_INTERVAL: 		/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_periodic_interval", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_periodic_interval", (char*)tmp); 

				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_INFORM_TIME: 			/* intiger */
			{
				char tmp[128];

				if( (ptr == NULL) || (ptr_size == 0)) {
					nvram_set("cwmp_periodic_time", "");
					tmp[0]=0;
				} else {
					snprintf(tmp, sizeof(tmp), "%d", (unsigned int)*(unsigned int*)ptr);
					nvram_set("cwmp_periodic_time", (char*)tmp); 

				}
				bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)tmp);
			}
			break;
		case CWMP_ACS_UPGRADESMANAGED: 	/* string */
			if( (ptr == NULL) || (ptr_size == 0)) {
				nvram_set("cwmp_acs_upgradesmanaged", "");
			} else {
				nvram_set("cwmp_acs_upgradesmanaged", (char*)ptr); 
			}
			bcmcfg_debug_printf(stderr, "[%s():%d] event=[%s] value=[%s]...\n", __FUNCTION__, __LINE__, bcm_event_str_get(api), (char*)ptr);
			break;
		default:
			bcmcfg_debug_printf(stderr, "[%s():%d] Unkown Event...\n", __FUNCTION__, __LINE__);
			break;
	}

	return 0;
}



/********************************************************************************/
/* Obj Method Sample*/
/********************************************************************************/
//static OBJ_SAMPLE_T *l_ObjSampleTbl=NULL;
static OBJ_SAMPLE_T *root_wlan_tbl = NULL;
static OBJ_SAMPLE_T *root_atc_tbl = NULL;
static OBJ_SAMPLE_T *root_PortMapTbl = NULL;

/********************************************************************************/
/* Obj Method Funcs */
/********************************************************************************/
/********************************************************************************/
/* return value  XXX : total chain num */
/********************************************************************************/
int bcm_cfg_chain_total( int api) 
{
	int num=0;
	OBJ_SAMPLE_T *entry;

	switch(api) {

		/* TODO fill body */
		/* ... */
		case CWMP_WLAN_CONF_TBL:
			entry=(OBJ_SAMPLE_T*)root_wlan_tbl;

			while(entry) {
				entry=entry->next;
				num++;
			}
			break;
		case CWMP_ATCADDR_TBL:
			entry=(OBJ_SAMPLE_T*)root_atc_tbl;

			while(entry) {
				entry=entry->next;
				num++;
			}
			break;
		case CWMP_PORTFRD_MAP_TBL:
			entry=(OBJ_SAMPLE_T*)root_PortMapTbl;

			while(entry) {
				entry=entry->next;
				num++;
			}
			break;
#if 0
		case CWMP_OBJ_SAMPLE_TBL: 	/* sample */
		{
			OBJ_SAMPLE_T *entry;

			entry=(OBJ_SAMPLE_T*)l_ObjSampleTbl;

			while(entry) {
				entry=entry->next;
				num++;
			}
			break;
		}
#endif
		default:
			fprintf(stderr, "[%s():%d] TODO...\n", __FUNCTION__, __LINE__);
			break;
	}

	return num;
}

/********************************************************************************/
/* return value : 0 = exist */
/*                1 = not exist */
/********************************************************************************/
int bcm_cfg_chain_get(int api, int id, void *ptr, int ptr_size)
{
	int idx=(-1);

	switch(api) {
		case CWMP_WLAN_CONF_TBL:
		{
			OBJ_SAMPLE_T *entry, *get;

			get = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_wlan_tbl;

			while (entry){
				idx++;
				if (idx == id) {
					get->InstanceNum = entry->InstanceNum;
					get->param	 	 = entry->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
		case CWMP_ATCADDR_TBL:
		{
			OBJ_SAMPLE_T *entry, *get;

			get = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_atc_tbl;

			while (entry){
				idx++;
				if (idx == id) {
					get->InstanceNum = entry->InstanceNum;
					get->param	 	 = entry->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
		case CWMP_PORTFRD_MAP_TBL:
		{
			OBJ_SAMPLE_T *entry, *get;

			get = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_PortMapTbl;

			while (entry){
				idx++;
				if (idx == id) {
					get->InstanceNum = entry->InstanceNum;
					get->param	 	 = entry->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
#if 0		
		case CWMP_OBJ_SAMPLE_TBL: 	/* sample */
			{
				OBJ_SAMPLE_T *entry, *get;

				get =(OBJ_SAMPLE_T*)ptr; 
				entry=(OBJ_SAMPLE_T*)l_ObjSampleTbl;

				while(entry) {
					idx++;

					if(idx == id) {
						get->InstanceNum = entry->InstanceNum;
						get->param 		= entry->param;
						return 1;
					}

					entry=entry->next;
				}

				return 0;
			}
#endif
		default:
			break;
	}

	fprintf(stderr, "[%s():%d] TODO...\n", __FUNCTION__, __LINE__);

	return 0;
}

/********************************************************************************/
/* return value : 0 = Error */
/*                1 = Success */
/********************************************************************************/
int bcm_cfg_chain_update(int api, int id, void *ptr, int ptr_size )
{
	int idx=(-1);

	switch(api) {

		case CWMP_WLAN_CONF_TBL:
		{
			OBJ_SAMPLE_T *entry, *update;

			update = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_wlan_tbl;

			while (entry){
				idx++;
				if (idx == id) {
					entry->InstanceNum = update->InstanceNum;
					entry->param	   = update->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
		case CWMP_ATCADDR_TBL:
		{
			OBJ_SAMPLE_T *entry, *update;

			update = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_atc_tbl;

			while (entry){
				idx++;
				if (idx == id) {
					entry->InstanceNum = update->InstanceNum;
					entry->param	   = update->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
		case CWMP_PORTFRD_MAP_TBL:
		{
			OBJ_SAMPLE_T *entry, *update;

			update = (OBJ_SAMPLE_T *)ptr;
			entry = (OBJ_SAMPLE_T *)root_PortMapTbl;

			while (entry){
				idx++;
				if (idx == id) {
					entry->InstanceNum = update->InstanceNum;
					entry->param	   = update->param;
					return 1;
				}
				entry = entry->next;
			}

			return 0;
		}
#if 0
		case CWMP_OBJ_SAMPLE_TBL: 	/* sample */
			{
				OBJ_SAMPLE_T *entry, *update;

				update =(OBJ_SAMPLE_T*)ptr; 
				entry=(OBJ_SAMPLE_T*)l_ObjSampleTbl;

				while(entry) {
					idx++;

					if(idx == id) {
						entry->InstanceNum 	= update->InstanceNum;
						entry->param 		= update->param;
						return 1;
					}

					entry=entry->next;
				}

				return 0;
			}

			break;
#endif
		default:
			break;
	}

	fprintf(stderr, "[%s():%d] TODO...\n", __FUNCTION__, __LINE__);

	return 1;
}

/********************************************************************************/
/* return value : 0 = Error */
/*                1 = Success */
/********************************************************************************/
int bcm_cfg_chain_add( int api, unsigned char *ptr, int ptr_size )
{
	int num;

	switch(api) {

		/* TODO fill body */
		/* ... */
		case CWMP_WLAN_CONF_TBL:
		{
			OBJ_SAMPLE_T *entry, *root;

			entry = (OBJ_SAMPLE_T *)ptr;

			num = bcm_cfg_chain_total(api);

			if (num==0) {
				root_wlan_tbl = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));
				if (root_wlan_tbl==NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(root_wlan_tbl, 0, sizeof(OBJ_SAMPLE_T));
				root_wlan_tbl->InstanceNum 	= entry->InstanceNum;
				root_wlan_tbl->param		= entry->param;
			}
			else {
				OBJ_SAMPLE_T	*add;
				
				root = (OBJ_SAMPLE_T *)root_wlan_tbl;
				add	 = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));

				if (add==NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(add, 0, sizeof(OBJ_SAMPLE_T));
				add->InstanceNum 	= entry->InstanceNum;
				add->param 			= entry->param;

				while( root->next ) {
					root = root->next;
				}

				root->next = add;
			}
			return 1;
		}
		case CWMP_ATCADDR_TBL:
		{
			OBJ_SAMPLE_T *entry, *root;

			entry = (OBJ_SAMPLE_T *)ptr;

			num = bcm_cfg_chain_total(api);

			if (num==0) {
				root_atc_tbl = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));
				if (root_atc_tbl==NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(root_atc_tbl, 0, sizeof(OBJ_SAMPLE_T));
				root_atc_tbl->InstanceNum 	= entry->InstanceNum;
				root_atc_tbl->param		= entry->param;
			}
			else {
				OBJ_SAMPLE_T	*add;
				
				root = (OBJ_SAMPLE_T *)root_atc_tbl;
				add	 = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));

				if (add==NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(add, 0, sizeof(OBJ_SAMPLE_T));
				add->InstanceNum 	= entry->InstanceNum;
				add->param 			= entry->param;

				while( root->next ) {
					root = root->next;
				}

				root->next = add;
			}
			return 1;
		}
		case CWMP_PORTFRD_MAP_TBL:
		{
			OBJ_SAMPLE_T *entry, *root;

			entry = (OBJ_SAMPLE_T *)ptr;

			num = bcm_cfg_chain_total(api);

			if (num==0) {
				root_PortMapTbl = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));
				if (root_PortMapTbl == NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(root_PortMapTbl, 0, sizeof(OBJ_SAMPLE_T));
				root_PortMapTbl->InstanceNum 	= entry->InstanceNum;
				root_PortMapTbl->param			= entry->param;
			}
			else {
				OBJ_SAMPLE_T	*add;
				
				root = (OBJ_SAMPLE_T *)root_PortMapTbl;
				add	 = (OBJ_SAMPLE_T *)malloc(sizeof(OBJ_SAMPLE_T));

				if (add==NULL) {
					fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
					return 0;
				}
				memset(add, 0, sizeof(OBJ_SAMPLE_T));
				add->InstanceNum 	= entry->InstanceNum;
				add->param 			= entry->param;

				while( root->next ) {
					root = root->next;
				}

				root->next = add;
			}
			return 1;
		}
#if 0
		case CWMP_OBJ_SAMPLE_TBL: 	/* sample */
			{
				OBJ_SAMPLE_T *root, *entry;

				entry = (OBJ_SAMPLE_T*)ptr;

				num = bcm_cfg_chain_total(api);
				if( num == 0 ) {
					l_ObjSampleTbl = (OBJ_SAMPLE_T*)malloc(sizeof(OBJ_SAMPLE_T));
					if( l_ObjSampleTbl == NULL) {
						fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
						return 0;
					}

					memset(l_ObjSampleTbl, 0, sizeof(OBJ_SAMPLE_T));
					l_ObjSampleTbl->InstanceNum = entry->InstanceNum;
					l_ObjSampleTbl->param 		= entry->param;
				} else {
					OBJ_SAMPLE_T *add;
					root = (OBJ_SAMPLE_T*)l_ObjSampleTbl;

					add = malloc(sizeof(OBJ_SAMPLE_T));
					if( add == NULL) {
						fprintf(stderr, "[%s():%d] malloc err..\n", __FUNCTION__, __LINE__);
						return 0;
					}

					memset(add, 0, sizeof(OBJ_SAMPLE_T));
					add->InstanceNum 	= entry->InstanceNum;
					add->param 			= entry->param;

					while( root->next ) {
						root = root->next;
					}

					root->next = add;
				}

				return 1;
			}
#endif
		default:
			break;
	}

	fprintf(stderr, "[%s():%d] TODO...\n", __FUNCTION__, __LINE__);

	return 1;
}

/********************************************************************************/
/* return value : 0 = Error */
/*                1 = Success */
/********************************************************************************/
int bcm_cfg_chain_delete( int api, int id )
{
	int idx=(-1);
	OBJ_SAMPLE_T *entry, *prev, *tmp;

	switch(api) {
	case CWMP_WLAN_CONF_TBL:
		entry = (OBJ_SAMPLE_T *)root_wlan_tbl;

		while(entry) {
			idx++;
			if (idx == id) {
				if (idx ==0) {
					tmp = entry->next;
					free(entry);
					root_wlan_tbl = (OBJ_SAMPLE_T*)tmp;
				} else {
					tmp = entry->next;
					free(entry);
					prev->next = tmp;
				}
				return 1;
			}
			prev=entry;
			entry=entry->next;
		}
		return 0;
	case CWMP_ATCADDR_TBL:
		entry = (OBJ_SAMPLE_T *)root_atc_tbl;

		while(entry) {
			idx++;
			if (idx == id) {
				if (idx ==0) {
					tmp = entry->next;
					free(entry);
					root_atc_tbl = (OBJ_SAMPLE_T*)tmp;
				} else {
					tmp = entry->next;
					free(entry);
					prev->next = tmp;
				}
				return 1;
			}
			prev=entry;
			entry=entry->next;
		}
		return 0;
	case CWMP_PORTFRD_MAP_TBL:
		entry = (OBJ_SAMPLE_T *)root_PortMapTbl;

		while(entry) {
			idx++;
			if (idx == id) {
				if (idx ==0) {
					tmp = entry->next;
					free(entry);
					root_PortMapTbl = (OBJ_SAMPLE_T*)tmp;
				} else {
					tmp = entry->next;
					free(entry);
					prev->next = tmp;
				}
				return 1;
			}
			prev=entry;
			entry=entry->next;
		}
		return 0;
#if 0		
		case CWMP_OBJ_SAMPLE_TBL: 	/* sample */
			{
				OBJ_SAMPLE_T *entry, *prev, *tmp;

				entry=(OBJ_SAMPLE_T*)l_ObjSampleTbl;

				while(entry) {
					idx++;

					if(idx == id) {
						if( idx == 0 ) {
							tmp = entry->next;
							free(entry);

							/* root */
							l_ObjSampleTbl=(OBJ_SAMPLE_T*)tmp;
						} else {
							tmp = entry->next;
							free(entry);
							prev->next = tmp;
						}

						return 1;
					}

					prev=entry;
					entry=entry->next;
				}

				return 0;
			}
#endif
		default:
			break;
	}

	fprintf(stderr, "[%s():%d] TODO...\n", __FUNCTION__, __LINE__);

	return 1;
}


#endif /* __BCM_CFG_API_C__ */

