obj-y += nettweak.o
nettweak-y := in_ipv4_addr.o unsol_neigh.o port_censor.o brforward_drop.o
CFLAGS_port_censor.o = -I$(CPKG_USER)/include -I$(srctree)/drivers/net/rtl819x
CFLAGS_unsol_neigh.o = -I$(CPKG_USER)/include -I$(srctree)/drivers/net/rtl819x
