#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1
PROG=/usr/sbin/portmon
UCICONF=portmon

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_append_param command "-F"
	procd_close_instance
}

reload_service()
{
	rc_procd stop_service "$@"
	rc_procd start_service "$@"
	return 0
}

service_triggers()
{
	procd_add_reload_trigger "${UCICONF}"
}

stop_service() {
	service_stop ${PROG}
}

